'use client';
import { useEffect, useRef, useState } from 'react';
import ShiftSimulator from './ShiftSimulator';
const COLS=7,ROWS=7,ROUND_SECONDS=45,START={x:3,y:6};
const RACKS=new Set(['1,1','2,1','4,1','5,1','1,3','2,3','4,3','5,3']);
const SPAWNS=[{x:0,y:1},{x:3,y:1},{x:6,y:1},{x:0,y:3},{x:3,y:3},{x:6,y:3},{x:1,y:5},{x:5,y:5}],DOCKS=[{x:0,y:6,label:'A'},{x:3,y:0,label:'B'},{x:6,y:6,label:'C'}];
function key(p){return `${p.x},${p.y}`}function randomJob(){return {pickup:SPAWNS[Math.floor(Math.random()*SPAWNS.length)],dock:DOCKS[Math.floor(Math.random()*DOCKS.length)]}}function blocked(x,y){return x<0||x>=COLS||y<0||y>=ROWS||RACKS.has(`${x},${y}`)}
function ForkliftIcon({carrying=false}){return <span className="forkliftSprite" aria-label="Stapler"><span className="forkBody"/><span className="forkCab"/><span className="forkMast"/><span className="forkTines"/><span className="wheel w1"/><span className="wheel w2"/>{carrying&&<span className="forkLoad">📦</span>}</span>}
export default function ForkliftRush({onClose}){const [sub,setSub]=useState('rush'),[pos,setPos]=useState(START),[job,setJob]=useState(()=>randomJob()),[carrying,setCarrying]=useState(false),[score,setScore]=useState(0),[time,setTime]=useState(ROUND_SECONDS),[running,setRunning]=useState(false),[deliveries,setDeliveries]=useState(0),[combo,setCombo]=useState(0),[message,setMessage]=useState('Hol die Palette und bring sie zum markierten Tor.'),timer=useRef(null),lastDelivery=useRef(0);
function start(){setPos(START);setJob(randomJob());setCarrying(false);setScore(0);setTime(ROUND_SECONDS);setDeliveries(0);setCombo(0);lastDelivery.current=0;setMessage('Los geht’s! Palette aufnehmen.');setRunning(true)}
useEffect(()=>{if(!running)return;timer.current=setInterval(()=>setTime(t=>{if(t<=1){clearInterval(timer.current);setRunning(false);setMessage('Schicht beendet! 🏁');return 0}return t-1}),1000);return()=>clearInterval(timer.current)},[running]);
function move(dx,dy){if(!running)return;setPos(p=>{const n={x:p.x+dx,y:p.y+dy};if(blocked(n.x,n.y)){setScore(s=>Math.max(0,s-10));setCombo(0);setMessage('Regal erwischt: −10 Punkte 💥');return p}if(!carrying&&key(n)===key(job.pickup)){setCarrying(true);setMessage(`Palette drauf! Jetzt zu Tor ${job.dock.label}.`)}else if(carrying&&key(n)===key(job.dock)){const now=Date.now(),fast=lastDelivery.current&&now-lastDelivery.current<9000,nextCombo=fast?Math.min(5,combo+1):1,earned=100+(nextCombo-1)*25;lastDelivery.current=now;setCombo(nextCombo);setDeliveries(d=>d+1);setCarrying(false);setScore(s=>s+earned);setTime(t=>Math.min(ROUND_SECONDS,t+1));setJob(randomJob());setMessage(`+${earned} Punkte${nextCombo>1?` · x${nextCombo} Tempo-Bonus`:''} · nur +1s Zeit`)}return n})}
useEffect(()=>{function down(e){const map={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0],w:[0,-1],s:[0,1],a:[-1,0],d:[1,0],W:[0,-1],S:[0,1],A:[-1,0],D:[1,0]},m=map[e.key];if(m){e.preventDefault();move(...m)}}window.addEventListener('keydown',down);return()=>window.removeEventListener('keydown',down)});
if(sub==='shift')return <ShiftSimulator onClose={()=>setSub('rush')}/>;
const rank=score>=1500?'Stapler-Legende 🏆':score>=1000?'Schichtmeister 🔥':score>=600?'Profi-Fahrer 😎':score>=300?'Routinier 📦':'Azubi';return <section className="gameShell card"><div className="gameHead"><div><span className="kicker">PAUSENMODUS</span><h1>🚧 Stapler Rush</h1></div><button className="secondary" onClick={onClose}>Zurück</button></div><button className="primary" style={{width:'100%',marginBottom:14}} onClick={()=>setSub('shift')}>🏭 NEU: Schicht-Simulator testen</button><div className="gameHud"><div><span>Zeit</span><strong>{time}s</strong></div><div><span>Punkte</span><strong>{score}</strong></div><div><span>Lieferungen</span><strong>{deliveries}</strong></div><div><span>Rang</span><strong>{rank}</strong></div></div><div className="gameBoard">{Array.from({length:ROWS*COLS},(_,i)=>{const x=i%COLS,y=Math.floor(i/COLS),k=`${x},${y}`,dock=DOCKS.find(d=>d.x===x&&d.y===y),isPickup=!carrying&&job.pickup.x===x&&job.pickup.y===y,isTarget=carrying&&job.dock.x===x&&job.dock.y===y,isPlayer=pos.x===x&&pos.y===y;return <div key={k} className={`gameCell ${RACKS.has(k)?'rack':''} ${dock?'dock':''} ${isTarget?'target':''} ${isPickup?'pickup':''}`}>{RACKS.has(k)?'▦':dock?`TOR ${dock.label}`:''}{isPickup&&<span className="pallet">📦</span>}{isPlayer&&<ForkliftIcon carrying={carrying}/>}</div>})}</div><p className="gameMessage">{message}</p>{!running&&<button className="primary gameStart" onClick={start}>{time===0?'Neue Schicht':'Schicht starten'}</button>}<div className="gameControls"><button onClick={()=>move(0,-1)}>▲</button><div><button onClick={()=>move(-1,0)}>◀</button><button onClick={()=>move(0,1)}>▼</button><button onClick={()=>move(1,0)}>▶</button></div></div><small className="gameTip">45 Sekunden · Lieferung +1s · Regal −10 Punkte · schnelle Lieferungen erhöhen den Punktebonus</small></section>}
