'use client';
import {useEffect,useRef,useState} from 'react';
import {practicalTaskCases,findingOptions,equipmentOptions,equipmentChecks,taskStages,evaluateTaskStep,summarizeTask} from './practical-task-data';
import {scoreAnswerHybrid} from './hybrid-score';
import {scoreAnswer} from './data';
import './practical-training.css';
import './stock-card.css';
export default function PracticalTask({onClose}){
 const [caseId,setCaseId]=useState(practicalTaskCases[0].id),[started,setStarted]=useState(false),[step,setStep]=useState(0),[findings,setFindings]=useState([]),[handling,setHandling]=useState(''),[device,setDevice]=useState(''),[checks,setChecks]=useState([]),[place,setPlace]=useState(''),[entries,setEntries]=useState([]),[result,setResult]=useState(null),[results,setResults]=useState([]),[busy,setBusy]=useState(false),[done,setDone]=useState(false);
 const generation=useRef(0),lock=useRef(false),recorded=useRef(false);useEffect(()=>()=>{generation.current++;lock.current=false},[]);
 const c=practicalTaskCases.find(c=>c.id===caseId),summary=summarizeTask(results),toggle=(setter,id)=>setter(old=>old.includes(id)?old.filter(x=>x!==id):[...old,id]);
 function reset(id=caseId){generation.current++;lock.current=false;recorded.current=false;setBusy(false);setCaseId(id);setStarted(false);setStep(0);setFindings([]);setHandling('');setDevice('');setChecks([]);setPlace('');setEntries([]);setResult(null);setResults([]);setDone(false)}
 function save(grade){if(recorded.current)return;recorded.current=true;setResult(grade);setResults(old=>[...old,{...grade,stage:taskStages[step],self:!!grade.self}])}
 async function check(){if(lock.current||recorded.current||result)return;lock.current=true;const ticket=++generation.current;setBusy(true);try{if(step!==1){save(evaluateTaskStep(c,step,{findings,device,checks,place,entries}));return}const grade=await scoreAnswerHybrid(handling,c.handling,scoreAnswer);if(ticket!==generation.current)return;if(grade.aiStatus?.includes('fehlgeschlagen'))setResult({unavailable:true});else save({score:grade.score,reason:grade.aiReason||c.handling.solution,critical:!!grade.aiReason?.includes('Bewertung auf höchstens 20 % begrenzt.')})}finally{if(ticket===generation.current){lock.current=false;setBusy(false)}}}
 function next(){generation.current++;lock.current=false;recorded.current=false;setResult(null);if(step===4)setDone(true);else setStep(s=>s+1)}
 function update(i,key,value){setEntries(old=>{const next=[...old];next[i]={...next[i],[key]:value};return next})}
 const canCheck=step===0||step===1&&handling.trim()||step===2&&device&&checks.length||step===3&&place||step===4&&c.card.movements.every((_,i)=>['incoming','outgoing','balance'].every(k=>entries[i]?.[k]?.trim()));
 return <section className="practiceShell"><header className="practiceHead"><div><span className="kicker">EIN AUFTRAG · FÜNF SCHRITTE</span><h1>Zusammenhängende Praxisaufgabe</h1><p>Lieferung prüfen, Abweichung behandeln, Arbeitsmittel und Lagerplatz wählen und den Bestand buchen.</p></div><button className="secondary" onClick={onClose}>← Praktische Abläufe</button></header>
 {!started?<div className="practicePanel"><label className="stockCaseLabel">Fall auswählen<select value={caseId} onChange={e=>reset(e.target.value)}>{practicalTaskCases.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><h2>{c.title}</h2><p>Du bist für die Warenannahme zuständig, unterwiesen und für die eingesetzten Geräte beauftragt. Die Arbeitsstelle ist nach betrieblichem Verfahren vorbereitet. In fünf Schritten bearbeitest du einen fiktiven Auftrag mit unmittelbarer Rückmeldung.</p><p>Jeder Schritt zählt gleich viel. Die Auswertung ist ein Trainingsstand und keine offizielle Prüfungsnote.</p><button className="primary" onClick={()=>setStarted(true)}>Praxisaufgabe starten</button></div>:done?<div className="practicePanel"><h2>{summary.percent}% Trainingsstand</h2>{summary.critical&&<p className="taskSafety" role="status">Sicherheitsfehler: Arbeitsmittel oder Lagerplatz erneut prüfen. Der Gesamtschnitt hebt eine gefährliche Entscheidung nicht auf.</p>}<div className="practiceReview">{results.map((r,i)=><details key={i} open={r.score<100}><summary>{r.score}% · {r.stage}{r.self?' · selbst eingeschätzt':''}</summary><p>{r.reason}</p></details>)}</div><div className="practiceLinks"><button onClick={()=>{reset();setStarted(true)}}>Fall erneut bearbeiten</button><button onClick={()=>reset()}>Anderen Fall auswählen</button></div></div>:<div className="practicePanel"><div className="practiceMeta"><span>Schritt {step+1} von 5 · {c.title}</span><button onClick={()=>reset()}>Zur Fallauswahl</button></div><h2>{taskStages[step]}</h2>
 {step===0&&<><div className="taskDocuments"><article><h3>Lieferschein {c.document.ref}</h3><dl><dt>Lieferant</dt><dd>{c.document.supplier}</dd><dt>Empfänger</dt><dd>{c.document.recipient}</dd><dt>Bestellung</dt><dd>{c.document.order}</dd><dt>Artikel</dt><dd>{c.article}</dd><dt>Menge</dt><dd>{c.ordered} Kartons × {c.perBox} Stück</dd></dl></article><article><h3>Tatsächliche Lieferung</h3><p>{c.physical}</p></article></div><p>Welche Abweichungen stellst du fest? Wähle alle zutreffenden Angaben; wenn du keine feststellst, kannst du ohne Markierung prüfen.</p><div className="taskChoices">{findingOptions.map(([id,label])=><label key={id}><input type="checkbox" checked={findings.includes(id)} disabled={!!result} onChange={()=>toggle(setFindings,id)}/>{label}</label>)}</div></>}
 {step===1&&<><p>Festgestellte Abweichung: {c.findings.map(id=>findingOptions.find(o=>o[0]===id)[1]).join(', ')}.</p><label className="practiceAnswer">{c.handling.question}<textarea value={handling} disabled={!!result||busy} onChange={e=>setHandling(e.target.value)} placeholder="Deine Maßnahmen in eigenen Worten"/></label></>}
 {step===2&&<><div className="taskSituation"><b>Stand nach Klärung</b><p>{c.resolution}</p></div><p>Die freigegebene Ladeeinheit wiegt einschließlich Palette {c.mass} kg. Sie soll auf 3 m Höhe eingelagert werden. Welches bereitgestellte Gerät ist dafür geeignet?</p><div className="taskChoices">{equipmentOptions.map(o=><label key={o.id}><input type="radio" name="taskDevice" checked={device===o.id} disabled={!!result} onChange={()=>setDevice(o.id)}/>{o.label}</label>)}</div><h3>Was ist vor dem Einsatz zu beachten?</h3><div className="taskChoices">{equipmentChecks.map(([id,label])=><label key={id}><input type="checkbox" checked={checks.includes(id)} disabled={!!result} onChange={()=>toggle(setChecks,id)}/>{label}</label>)}</div></>}
 {step===3&&<><p>Du verwendest jetzt den freigegebenen Frontgabelstapler. Die Last wiegt {c.mass} kg. Artikel und Lagerbedingungen passen zu A und B; die Lasten sind gleichmäßig verteilt. Welcher Platz ist geeignet?</p><div className="taskChoices">{[['A','A-02-03: Fachlast 600 kg, bisher 250 kg belegt; Feldlast 1.500 kg, bisher 1.000 kg belegt.'],['B','B-01-01: Fachlast 600 kg, bisher 400 kg belegt; Feldlast 1.500 kg, bisher 1.000 kg belegt.'],['C','Gang vor dem Notausgang: momentan leer, als Fluchtweg gekennzeichnet.']].map(([id,label])=><label key={id}><input type="radio" name="taskPlace" checked={place===id} disabled={!!result} onChange={()=>setPlace(id)}/>{label}</label>)}</div></>}
 {step===4&&<><div className="stockMeta"><strong>{c.card.article}</strong><span>Lagerplatz {c.card.place} · Buchungseinheit: Stück</span><span>Anfangsbestand: {c.card.opening} Stück</span></div><p>{c.resolution}</p><p>Führe die Fachkarte des verfügbaren Bestands auf A-02-03. Gesperrte oder nicht gelieferte Ware wird hier nicht gebucht. Trage 0 ein, wenn es keinen Zugang oder Abgang gibt.</p><div className="stockRows">{c.card.movements.map((m,i)=><article key={m.ref} className="stockRow"><div className="stockDocument"><span>{m.date} · {m.ref}</span><p>{m.text}</p></div><div className="stockInputs">{[['incoming','Zugang'],['outgoing','Abgang'],['balance','Bestand']].map(([key,label])=><label key={key}>{label}<input inputMode="decimal" aria-label={`${label} Bewegung ${i+1}`} value={entries[i]?.[key]||''} disabled={!!result} onChange={e=>update(i,key,e.target.value)}/>{result?.stock&&<small>{result.stock.rows[i].correct[key]?'✓ Richtig':key==='balance'&&result.stock.rows[i].followThrough?'Übertrag richtig gerechnet':`Richtig: ${result.stock.rows[i].expected[key]}`}</small>}</label>)}</div></article>)}</div></>}
 {!result?<button className="primary" disabled={!canCheck||busy} onClick={check}>{busy?'Antwort wird geprüft …':'Schritt prüfen'}</button>:<div className="practiceFeedback" role="status">{result.unavailable?<><p>Die Antwortprüfung ist gerade nicht erreichbar. Vergleiche deine Maßnahmen mit der Lösung:</p><p>{c.handling.solution}</p><div className="practiceLinks"><button onClick={()=>save({score:0,reason:c.handling.solution,self:true,critical:false})}>Noch unsicher</button><button onClick={()=>save({score:100,reason:c.handling.solution,self:true,critical:false})}>Gewusst</button></div></>:<><h3>{result.score}% für diesen Schritt</h3>{result.critical&&<p className="taskSafety">Sicherheitsfehler – die Entscheidung muss korrigiert werden.</p>}<p>{result.reason}</p><button className="primary" onClick={next}>{step===4?'Aufgabe auswerten':'Nächster Schritt'}</button></>}</div>}</div>}
 </section>;
}
