'use client';
import {useEffect,useRef,useState} from 'react';
import {practicalAreas,practicalTrainingPool} from './practical-training-data';
import {randomPick} from './smart-selection';
import {scoreAnswer} from './data';
import {scoreAnswerHybrid} from './hybrid-score';
import './practical-training.css';
export default function PracticalTraining({onClose,onSigns,onTask,onStock}){
 const [area,setArea]=useState('all'),[questions,setQuestions]=useState([]),[index,setIndex]=useState(0),[answer,setAnswer]=useState(''),[result,setResult]=useState(null),[results,setResults]=useState([]),[busy,setBusy]=useState(false),[done,setDone]=useState(false);
 const generation=useRef(0),lock=useRef(false),recorded=useRef(false);useEffect(()=>()=>{generation.current++;lock.current=false},[]);
 const current=questions[index],pool=practicalTrainingPool(area),title=area==='all'?'Praktische Abläufe':practicalAreas.find(a=>a.id===area)?.title;
 function start(id='all',selected=null){generation.current++;lock.current=false;recorded.current=false;setBusy(false);setArea(id);setQuestions(selected||randomPick(practicalTrainingPool(id),id==='all'?20:10));setIndex(0);setAnswer('');setResult(null);setResults([]);setDone(false)}
 function menu(){generation.current++;lock.current=false;setBusy(false);setQuestions([]);setDone(false)}
 async function check(){if(lock.current||result||!answer.trim())return;lock.current=true;const ticket=++generation.current;setBusy(true);try{const grade=await scoreAnswerHybrid(answer,current,scoreAnswer);if(ticket!==generation.current)return;if(grade.aiStatus?.includes('fehlgeschlagen')){setResult({unavailable:true,reason:'Die Antwortprüfung ist gerade nicht erreichbar. Vergleiche deine Antwort mit der Lösung und schätze dich selbst ein.'});return}save(grade.score,grade.aiReason)}finally{if(ticket===generation.current){lock.current=false;setBusy(false)}}}
 function save(score,reason=''){if(recorded.current)return;recorded.current=true;setResult({score,reason});setResults(old=>[...old,{q:current,answer,score}])}
 function next(){generation.current++;recorded.current=false;if(index+1===questions.length)setDone(true);else{setIndex(i=>i+1);setAnswer('');setResult(null)}}
 return <section className="practiceShell"><header className="practiceHead"><div><span className="kicker">PRAXIS ÜBEN</span><h1>{title}</h1><p>Warenannahme, Einlagern, Arbeitsmittel und Sicherheit gezielt trainieren.</p></div><button className="secondary" onClick={onClose}>← Praxiswelt</button></header>
 {!questions.length?<><div className="practiceStart"><button className="primary" onClick={()=>start()}>20 gemischte Fragen starten</button><p>{practicalTrainingPool().length} Aufgaben zu praktischen Abläufen · Antworten in eigenen Worten und Rechenaufgaben</p></div><div className="practiceAreas">{practicalAreas.map(a=><button key={a.id} className="practiceArea" onClick={()=>start(a.id)}><span>{a.icon}</span><strong>{a.title}</strong><small>{a.description}</small><b>{practicalTrainingPool(a.id).length} Aufgaben →</b></button>)}</div><div className="practiceLinks"><button onClick={onSigns}>Sicherheitszeichen üben</button><button onClick={onStock}>Lagerfachkarte ausfüllen</button><button onClick={onTask}>Zusammenhängende Praxisaufgabe</button></div></>:done?<div className="practicePanel"><h2>{Math.round(results.reduce((n,r)=>n+r.score,0)/results.length)}% im Training</h2><p>{results.length} Aufgaben bearbeitet. Selbst eingeschätzte Antworten zählen nur in dieser Runde.</p><div className="practiceReview">{results.filter(r=>r.score<100).map(r=><details key={r.q.id}><summary>{r.score}% · {r.q.question}</summary><p><b>Deine Antwort:</b> {r.answer}</p><p><b>Lösung:</b> {r.q.solution}</p></details>)}</div><div className="practiceLinks"><button onClick={()=>start(area)}>Neue Runde</button>{results.some(r=>r.score<80)&&<button onClick={()=>start(area,results.filter(r=>r.score<80).map(r=>r.q))}>Unsichere Aufgaben wiederholen</button>}<button onClick={menu}>Themen auswählen</button></div></div>:<div className="practicePanel"><div className="practiceMeta"><span>Frage {index+1} von {questions.length} · {current.topic}</span><button onClick={menu}>Themen auswählen</button></div><h2>{current.question}</h2><label className="practiceAnswer">Deine Antwort<textarea value={answer} inputMode={current.type==='number'?'decimal':'text'} disabled={busy||!!result} onChange={e=>setAnswer(e.target.value)} placeholder={current.type==='number'?'Ergebnis eingeben':'In eigenen Worten antworten'}/></label>{!result?<button className="primary" disabled={busy||!answer.trim()} onClick={check}>{busy?'Antwort wird geprüft …':'Antwort prüfen'}</button>:<div className="practiceFeedback" role="status">{result.unavailable?<><p>{result.reason}</p><p><b>Lösung:</b> {current.solution}</p><div className="practiceLinks"><button onClick={()=>save(0,'Selbst eingeschätzt')}>Noch unsicher</button><button onClick={()=>save(100,'Selbst eingeschätzt')}>Gewusst</button></div></>:<><h3>{result.score}%</h3>{result.reason&&<p>{result.reason}</p>}<p><b>Lösung:</b> {current.solution}</p><button className="primary" onClick={next}>{index+1===questions.length?'Training auswerten':'Nächste Frage'}</button></>}</div>}</div>}
 </section>;
}
