'use client';
import {useState} from 'react';
import ShiftSimulator from './ShiftSimulator';
import WarehouseTycoon from './WarehouseTycoon';
import DocumentWorkshop from './DocumentWorkshop';
import PurchasingDuel from './PurchasingDuel';
import SafetySigns from './SafetySigns';
import StockCardWorkshop from './StockCardWorkshop';
import PracticalTraining from './PracticalTraining';
import PracticalTask from './PracticalTask';
export default function Praxiswelt({onClose,initialSection='menu'}) {
const [sub,setSub]=useState(initialSection);
if(sub==='practical')return <PracticalTraining onClose={()=>setSub('menu')} onSigns={()=>setSub('signs')} onStock={()=>setSub('stock')} onTask={()=>setSub('task')}/>;if(sub==='task')return <PracticalTask onClose={()=>setSub('practical')}/>;if(sub==='shift')return <ShiftSimulator onClose={()=>setSub('menu')}/>;if(sub==='tycoon')return <WarehouseTycoon onClose={()=>setSub('menu')}/>;if(sub==='docs')return <DocumentWorkshop onClose={()=>setSub('menu')}/>;if(sub==='buy')return <PurchasingDuel onClose={()=>setSub('menu')}/>;if(sub==='stock')return <StockCardWorkshop onClose={()=>setSub('menu')}/>;if(sub==='signs')return <SafetySigns onClose={()=>setSub('menu')}/>;
return <section className="activityHub"><div className="activityHead"><div><span className="kicker">PRAXISWELT</span><h1>Training & Simulationen</h1><p>Logistik anwenden statt nur Fragen beantworten.</p></div><button className="secondary" onClick={onClose}>Zurück</button></div><div className="activityGrid"><button className="activityCard" onClick={()=>setSub('practical')}><span className="activityIcon">📋</span><div><strong>Praktische Abläufe</strong><small>Warenannahme · Einlagern · Arbeitsmittel · Sicherheit</small></div><b>Üben →</b></button><button className="activityCard" onClick={()=>setSub('shift')}><span className="activityIcon">🏭</span><div><strong>Schicht-Simulator</strong><small>Entscheidungen treffen · Folgen erleben · Schicht auswerten</small></div><b>Starten →</b></button><button className="activityCard" onClick={()=>setSub('tycoon')}><span className="activityIcon">🔥</span><div><strong>Lager unter Druck</strong><small>Vorgänge steuern · Fristen · Qualität · Sicherheit</small></div><b>Übernehmen →</b></button><button className="activityCard" onClick={()=>setSub('docs')}><span className="activityIcon">🧾</span><div><strong>Dokumenten-Werkstatt</strong><small>Situationen prüfen · Abweichungen selbst entdecken</small></div><b>Prüfen →</b></button><button className="activityCard" onClick={()=>setSub('buy')}><span className="activityIcon">🤝</span><div><strong>Einkaufs-Duell</strong><small>Angebote vergleichen · Bezugspreis · Termin · Qualität</small></div><b>Vergeben →</b></button><button className="activityCard" onClick={()=>setSub('signs')}><span className="activityIcon">🔵</span><div><strong>Sicherheitszeichen</strong><small>Fünf Zeichenarten & GHS · Bilder lernen · 10er-Abfrage</small></div><b>Lernen →</b></button><button className="activityCard" onClick={()=>setSub('stock')}><span className="activityIcon">📝</span><div><strong>Lagerfachkarte</strong><small>Belege lesen · Mengen eintragen · Bestand fortschreiben</small></div><b>Ausfüllen →</b></button></div></section>;

}
