// v0.7: Ausbau Lernfelder 9–12 mit praxisnahen Freitext- und Multiple-Choice-Aufgaben.
export const v07Questions = [
// LF9 – Güter versenden
{id:'v07-9-01',field:9,topic:'KEP',difficulty:1,type:'mc',question:'Wofür steht die Abkürzung KEP?',options:['Kurier-, Express- und Paketdienste','Kosten-, Einkaufs- und Produktionsplanung','Kontrolle europäischer Paletten','Kombinierte Exportpapiere'],correct:[0],solution:'KEP steht für Kurier-, Express- und Paketdienste.'},
{id:'v07-9-02',field:9,topic:'Versandarten',difficulty:2,type:'mc',question:'Welche Kriterien beeinflussen die Wahl einer geeigneten Versandart?',options:['Gewicht und Abmessungen','Liefertermin','Kosten','Lieblingsfarbe des Empfängers'],correct:[0,1,2],solution:'Versandart und Dienstleister werden unter anderem nach Gewicht/Abmessungen, gewünschter Laufzeit bzw. Liefertermin und Kosten ausgewählt.'},
{id:'v07-9-03',field:9,topic:'Frachtpapiere',difficulty:2,type:'free',question:'Nenne vier Angaben, die für einen Transport- oder Frachtauftrag wichtig sein können.',keywords:['absender','empfänger','gewicht','menge','art','bezeichnung','adresse','frachtführer','packstücke','termin'],minHits:4,solution:'Typische Angaben sind Absender, Empfänger, Art und Menge bzw. Packstückzahl der Güter, Gewicht sowie gegebenenfalls Termine und besondere Transporthinweise.'},
{id:'v07-9-04',field:9,topic:'Versandarten',difficulty:2,type:'free',question:'Ein Kunde benötigt eine kleine Sendung besonders schnell. Welche Versandlösung liegt nahe und warum?',keywords:['express','kep','schnell','laufzeit','termin','paket','kurier'],minHits:2,solution:'Je nach Größe und Dringlichkeit bietet sich ein Express- oder Kurierdienst aus dem KEP-Bereich an, weil kurze bzw. definierte Laufzeiten im Vordergrund stehen.'},
{id:'v07-9-05',field:9,topic:'Frachtpapiere',difficulty:2,type:'mc',question:'Warum müssen Versandpapiere und tatsächliche Sendung übereinstimmen?',options:['Damit Empfänger, Art und Menge korrekt zugeordnet werden können','Damit Fehlleitungen und Abweichungen vermieden werden','Weil das Gewicht grundsätzlich unwichtig ist','Damit Transportdaten nachvollziehbar sind'],correct:[0,1,3],solution:'Korrekte Versanddaten ermöglichen eindeutige Zuordnung und Nachvollziehbarkeit und reduzieren Fehlleitungen sowie Mengen- oder Identifikationsfehler.'},
{id:'v07-9-06',field:9,topic:'KEP',difficulty:2,type:'mc',question:'Welche Merkmale sind für Paketdienste typisch?',options:['Standardisierte Sendungsabwicklung','Sendungsverfolgung ist häufig möglich','Geeignet für viele kleinere Sendungen','Ausschließlich komplette Lkw-Ladungen'],correct:[0,1,2],solution:'Paketdienste arbeiten stark standardisiert, bieten häufig Tracking und transportieren vor allem kleinere, paketfähige Sendungen.'},
{id:'v07-9-07',field:9,topic:'Versandarten',difficulty:3,type:'free',question:'Warum ist die billigste Versandart nicht automatisch die wirtschaftlichste?',keywords:['lieferzeit','termin','schaden','zuverlässigkeit','service','kosten','kunde','reklamation'],minHits:3,solution:'Neben dem reinen Preis zählen unter anderem Laufzeit, Termintreue, Zuverlässigkeit, Schadensrisiko und Service. Verspätungen oder Schäden können zusätzliche Kosten und Reklamationen verursachen.'},
{id:'v07-9-08',field:9,topic:'Frachtpapiere',difficulty:2,type:'mc',question:'Was solltest du vor Übergabe einer Sendung an den Frachtführer kontrollieren?',options:['Versandstücke und Kennzeichnung','Begleitpapiere','Empfängerangaben','Private Urlaubsplanung des Fahrers'],correct:[0,1,2],solution:'Vor der Übergabe sollten Sendung, Kennzeichnung und erforderliche Begleitpapiere auf Vollständigkeit und Übereinstimmung geprüft werden.'},
{id:'v07-9-09',field:9,topic:'KEP',difficulty:2,type:'free',question:'Welchen Nutzen hat eine Sendungsverfolgung für Betrieb und Kunden?',keywords:['status','tracking','nachverfolgung','kunde','zustellung','lieferung','information','reklamation'],minHits:2,solution:'Tracking macht den aktuellen Sendungsstatus nachvollziehbar, erleichtert Kundeninformationen und hilft bei der Klärung von Verzögerungen oder fehlenden Sendungen.'},
{id:'v07-9-10',field:9,topic:'Versandarten',difficulty:3,type:'mc',question:'Eine Sendung ist sehr schwer und sperrig. Welche Aussage ist am sinnvollsten?',options:['Versandart nach Gewicht, Abmessungen und Transportanforderungen auswählen','Immer als Standardpaket versenden','Gewicht spielt bei der Versandplanung keine Rolle','Kennzeichnung kann entfallen'],correct:[0],solution:'Bei schweren oder sperrigen Gütern müssen Versandart und Verkehrsträger zu Abmessungen, Gewicht und Anforderungen der Sendung passen.'},

// LF10 – Logistische Prozesse optimieren
{id:'v07-10-01',field:10,topic:'KVP',difficulty:1,type:'mc',question:'Was ist das Grundprinzip des KVP?',options:['Prozesse fortlaufend in kleinen Schritten verbessern','Nur einmal jährlich Änderungen zulassen','Fehler grundsätzlich verbergen','Bestände möglichst stark erhöhen'],correct:[0],solution:'Der Kontinuierliche Verbesserungsprozess setzt auf fortlaufende, häufig kleine Verbesserungen von Abläufen.'},
{id:'v07-10-02',field:10,topic:'Qualität',difficulty:1,type:'mc',question:'Welche Reihenfolge beschreibt den PDCA-Zyklus richtig?',options:['Plan – Do – Check – Act','Plan – Check – Do – Stop','Do – Act – Plan – Delete','Check – Plan – Stop – Act'],correct:[0],solution:'PDCA bedeutet Plan, Do, Check, Act: planen, umsetzen, Ergebnis prüfen und daraus Maßnahmen bzw. Standards ableiten.'},
{id:'v07-10-03',field:10,topic:'Lean',difficulty:2,type:'free',question:'Nenne drei Beispiele für Verschwendung in einem Lagerprozess.',keywords:['warten','wege','transport','bestand','fehler','nacharbeit','bewegung','überproduktion','suchen'],minHits:3,solution:'Beispiele sind unnötige Wege und Transporte, Warte- und Suchzeiten, überhöhte Bestände, Fehler und Nacharbeit oder unnötige Bewegungen.'},
{id:'v07-10-04',field:10,topic:'KVP',difficulty:2,type:'free',question:'Warum sollten Mitarbeiter aus dem operativen Lager in Verbesserungsprozesse einbezogen werden?',keywords:['erfahrung','praxis','wissen','problem','ablauf','idee','akzeptanz','mitarbeiter'],minHits:2,solution:'Mitarbeiter kennen die täglichen Abläufe und Probleme aus der Praxis. Ihr Wissen kann realistische Verbesserungen liefern und die Akzeptanz neuer Abläufe erhöhen.'},
{id:'v07-10-05',field:10,topic:'Lean',difficulty:2,type:'mc',question:'Welche Maßnahmen passen zu Lean Management?',options:['Unnötige Wege reduzieren','Suchzeiten verringern','Fehlerquellen beseitigen','Bestände ohne Bedarf erhöhen'],correct:[0,1,2],solution:'Lean konzentriert sich auf Wertschöpfung und die Verringerung von Verschwendung, etwa unnötigen Wegen, Suchzeiten und Fehlern.'},
{id:'v07-10-06',field:10,topic:'Qualität',difficulty:2,type:'free',question:'Ein Kommissionierfehler tritt immer wieder auf. Wie würdest du nach dem PDCA-Prinzip vorgehen?',keywords:['plan','ursache','maßnahme','do','umsetzen','check','prüfen','act','standard'],minHits:4,solution:'Problem und Ursache analysieren und Maßnahme planen (Plan), Maßnahme testen (Do), Wirkung prüfen (Check) und erfolgreiche Lösung standardisieren bzw. bei Bedarf anpassen (Act).'},
{id:'v07-10-07',field:10,topic:'Qualität',difficulty:2,type:'mc',question:'Welche Aussage zum Qualitätsmanagement ist richtig?',options:['Fehlervermeidung ist meist sinnvoller als reine Fehlerkorrektur','Qualität betrifft nur die Endkontrolle','Reklamationen haben nichts mit Prozessqualität zu tun','Dokumentierte Standards sind grundsätzlich unnötig'],correct:[0],solution:'Qualitätsmanagement soll Fehler möglichst bereits im Prozess vermeiden und nicht erst am Ende entdecken.'},
{id:'v07-10-08',field:10,topic:'KVP',difficulty:3,type:'mc',question:'Welche Kennzahl kann zeigen, ob eine Verbesserung beim Kommissionieren wirkt?',options:['Fehlerquote','Kommissionierzeit','Leistung pro Stunde','Alle genannten'],correct:[3],solution:'Je nach Verbesserungsziel können Fehlerquote, benötigte Zeit und Kommissionierleistung geeignete Kennzahlen sein.'},
{id:'v07-10-09',field:10,topic:'Lean',difficulty:3,type:'free',question:'Warum kann ein sehr hoher Lagerbestand aus Lean-Sicht problematisch sein?',keywords:['kapital','platz','verschwendung','problem','fehler','verbergen','kosten','bestand'],minHits:3,solution:'Überhöhte Bestände binden Kapital und Fläche, verursachen Kosten und können Prozessprobleme oder schlechte Planung verdecken.'},
{id:'v07-10-10',field:10,topic:'Qualität',difficulty:2,type:'mc',question:'Was bedeutet das Null-Fehler-Prinzip als Zielvorstellung?',options:['Fehler von Anfang an möglichst vermeiden','Fehler sind erlaubt, solange niemand sie meldet','Kontrollen vollständig abschaffen','Nur Kunden dürfen Fehler entdecken'],correct:[0],solution:'Das Null-Fehler-Prinzip richtet Prozesse darauf aus, Fehler möglichst bereits bei ihrer Entstehung zu vermeiden.'},

// LF11 – Güter beschaffen
{id:'v07-11-01',field:11,topic:'Bestellverfahren',difficulty:1,type:'mc',question:'Wann wird beim Bestellpunktverfahren eine Bestellung ausgelöst?',options:['Wenn der Meldebestand erreicht oder unterschritten wird','Immer am ersten Montag des Monats','Erst bei Bestand null','Nur nach der Inventur'],correct:[0],solution:'Beim Bestellpunktverfahren löst das Erreichen bzw. Unterschreiten des Meldebestands den Bestellvorgang aus.'},
{id:'v07-11-02',field:11,topic:'Bestellverfahren',difficulty:2,type:'mc',question:'Was kennzeichnet das Bestellrhythmusverfahren?',options:['Bestellungen werden zu festgelegten Zeitpunkten geprüft bzw. ausgelöst','Bestellung erfolgt ausschließlich bei Bestand null','Es gibt grundsätzlich keine Bestandskontrolle','Lieferzeit spielt nie eine Rolle'],correct:[0],solution:'Beim Bestellrhythmusverfahren wird der Bestand in festgelegten Zeitabständen geprüft und entsprechend dem Bedarf bestellt.'},
{id:'v07-11-03',field:11,topic:'Lieferanten',difficulty:2,type:'free',question:'Nenne fünf Kriterien für eine Lieferantenbewertung.',keywords:['preis','qualität','termintreue','lieferzeit','zuverlässigkeit','service','konditionen','flexibilität'],minHits:5,solution:'Mögliche Kriterien sind Preis, Qualität, Lieferzeit, Termintreue, Zuverlässigkeit, Service, Flexibilität und Zahlungs- bzw. Lieferkonditionen.'},
{id:'v07-11-04',field:11,topic:'Beschaffung',difficulty:2,type:'free',question:'Warum ist der niedrigste Einstandspreis allein kein ausreichendes Kriterium für die Lieferantenauswahl?',keywords:['qualität','lieferzeit','termintreue','zuverlässigkeit','kosten','service','folgekosten'],minHits:3,solution:'Schlechte Qualität, lange Lieferzeiten oder mangelnde Termintreue können Folgekosten verursachen. Deshalb muss die Lieferantenleistung insgesamt betrachtet werden.'},
{id:'v07-11-05',field:11,topic:'Beschaffung',difficulty:2,type:'mc',question:'Welche Ziele können sich bei der Beschaffung widersprechen?',options:['Niedrige Bestände und hohe Lieferbereitschaft','Niedrige Einkaufspreise und hohe Qualität','Kurze Lieferzeit und hohe Versorgungssicherheit','Alle genannten können Zielkonflikte enthalten'],correct:[3],solution:'Beschaffung muss häufig Zielkonflikte zwischen Kosten, Qualität, Bestand, Lieferzeit und Versorgungssicherheit ausgleichen.'},
{id:'v07-11-06',field:11,topic:'Bestellverfahren',difficulty:2,type:'free',question:'Erkläre, warum der Mindestbestand bei der Berechnung des Meldebestands berücksichtigt wird.',keywords:['reserve','sicherheit','lieferverzögerung','mehrverbrauch','puffer','fehlmenge'],minHits:2,solution:'Der Mindestbestand dient als Sicherheitsreserve. Er soll während unerwarteter Lieferverzögerungen oder höherem Verbrauch vor Fehlmengen schützen.'},
{id:'v07-11-07',field:11,topic:'Lieferanten',difficulty:2,type:'mc',question:'Ein Lieferant ist etwas teurer, liefert aber fast immer pünktlich und fehlerfrei. Welche Aussage ist richtig?',options:['Er kann insgesamt wirtschaftlicher sein','Er ist wegen des höheren Preises automatisch ungeeignet','Qualität und Termintreue dürfen nicht bewertet werden','Nur der Listenpreis zählt'],correct:[0],solution:'Gesamtkosten und Lieferleistung sind entscheidend. Gute Qualität und Termintreue können Mehrkosten durch Störungen, Reklamationen und Eilbeschaffung vermeiden.'},
{id:'v07-11-08',field:11,topic:'Beschaffung',difficulty:3,type:'free',question:'Nenne drei mögliche Folgen einer verspäteten Materiallieferung.',keywords:['produktion','stillstand','fehlmenge','kunde','liefertermin','eilbeschaffung','kosten','verzug'],minHits:3,solution:'Mögliche Folgen sind Produktions- oder Lieferunterbrechungen, Fehlmengen, verspätete Kundenlieferungen und zusätzliche Kosten durch Eilbeschaffung.'},
{id:'v07-11-09',field:11,topic:'Lieferanten',difficulty:2,type:'mc',question:'Welche Daten eignen sich für eine objektive Lieferantenbewertung?',options:['Reklamationsquote','Termintreue','Preisniveau','Persönliche Sympathie allein'],correct:[0,1,2],solution:'Messbare Kriterien wie Reklamationsquote, Termintreue und Preise ermöglichen eine nachvollziehbare Lieferantenbewertung.'},
{id:'v07-11-10',field:11,topic:'Bestellverfahren',difficulty:3,type:'mc',question:'Der Tagesverbrauch steigt dauerhaft, Lieferzeit und Mindestbestand bleiben unverändert. Was geschieht mit dem Meldebestand?',options:['Er steigt','Er sinkt','Er bleibt gleich','Er wird null'],correct:[0],solution:'Meldebestand = Tagesverbrauch × Lieferzeit + Mindestbestand. Steigt der Tagesverbrauch, steigt bei sonst gleichen Werten auch der Meldebestand.'},

// LF12 – Kennzahlen ermitteln und auswerten
{id:'v07-12-01',field:12,topic:'Lagerkennzahlen',difficulty:1,type:'mc',question:'Was beschreibt die Umschlagshäufigkeit?',options:['Wie oft sich der durchschnittliche Lagerbestand im Zeitraum erneuert','Wie viele Mitarbeiter im Lager arbeiten','Wie groß das Gebäude ist','Wie viele Lieferanten vorhanden sind'],correct:[0],solution:'Die Umschlagshäufigkeit zeigt, wie oft der durchschnittliche Lagerbestand innerhalb eines Zeitraums umgesetzt bzw. erneuert wird.'},
{id:'v07-12-02',field:12,topic:'Lagerkennzahlen',difficulty:2,type:'mc',question:'Welche Aussage ist grundsätzlich richtig?',options:['Hohe Umschlagshäufigkeit geht tendenziell mit kurzer Lagerdauer einher','Hohe Umschlagshäufigkeit bedeutet immer hohen Bestand','Lagerdauer und Umschlag haben keinen Zusammenhang','Eine kurze Lagerdauer erhöht zwangsläufig den Bestand'],correct:[0],solution:'Umschlagshäufigkeit und durchschnittliche Lagerdauer verhalten sich grundsätzlich umgekehrt: höherer Umschlag bedeutet tendenziell kürzere Lagerdauer.'},
{id:'v07-12-03',field:12,topic:'Kosten',difficulty:2,type:'free',question:'Nenne vier Kosten oder Risiken, die durch hohe Lagerbestände entstehen können.',keywords:['kapitalbindung','raum','platz','personal','versicherung','schwund','verderb','veraltung','beschädigung','kosten'],minHits:4,solution:'Beispiele sind Kapitalbindung, Raum- und Personalkosten, Versicherung sowie Risiken durch Schwund, Verderb, Veralterung oder Beschädigung.'},
{id:'v07-12-04',field:12,topic:'Wirtschaftlichkeit',difficulty:2,type:'mc',question:'Warum sollte eine Kennzahl nicht isoliert bewertet werden?',options:['Weil Verbesserungen einer Kennzahl Nachteile an anderer Stelle verursachen können','Weil Kennzahlen grundsätzlich nutzlos sind','Weil nur absolute Bestände zählen','Weil Wirtschaftlichkeit nicht messbar ist'],correct:[0],solution:'Kennzahlen hängen zusammen. Ein extrem niedriger Bestand kann etwa Lagerkosten senken, gleichzeitig aber Fehlmengen und schlechtere Lieferbereitschaft verursachen.'},
{id:'v07-12-05',field:12,topic:'Lagerkennzahlen',difficulty:2,type:'free',question:'Wie wirkt sich eine höhere Umschlagshäufigkeit bei sonst gleichen Bedingungen typischerweise auf Kapitalbindung und Lagerdauer aus?',keywords:['sinkt','geringer','kapitalbindung','lagerdauer','kürzer','umschlag'],minHits:3,solution:'Bei höherer Umschlagshäufigkeit sinken typischerweise die durchschnittliche Lagerdauer und damit tendenziell auch die Kapitalbindung.'},
{id:'v07-12-06',field:12,topic:'Wirtschaftlichkeit',difficulty:3,type:'mc',question:'Welche Entwicklung wäre grundsätzlich positiv, sofern die Lieferbereitschaft stabil bleibt?',options:['Kürzere durchschnittliche Lagerdauer','Mehr Schwund','Höhere Fehlerquote','Mehr unnötige Bestände'],correct:[0],solution:'Eine kürzere Lagerdauer kann Kapitalbindung und lagerzeitabhängige Kosten reduzieren, sofern die Versorgung bzw. Lieferbereitschaft nicht leidet.'},
{id:'v07-12-07',field:12,topic:'Kosten',difficulty:2,type:'free',question:'Was versteht man unter Kapitalbindung im Lager?',keywords:['geld','kapital','bestand','ware','gebunden','nicht verfügbar','liquidität'],minHits:2,solution:'In gelagerter Ware steckt eingesetztes Kapital. Solange die Ware im Bestand liegt, steht dieses Geld nicht anderweitig zur Verfügung.'},
{id:'v07-12-08',field:12,topic:'Lagerkennzahlen',difficulty:2,type:'mc',question:'Wozu dient die Inventurdifferenz?',options:['Sie zeigt die Abweichung zwischen Buchbestand und tatsächlich gezähltem Bestand','Sie berechnet die Lieferzeit','Sie bestimmt die Zahl der Mitarbeiter','Sie ersetzt die Inventur'],correct:[0],solution:'Die Inventurdifferenz ist die Abweichung zwischen Soll- bzw. Buchbestand und dem bei der Inventur festgestellten Istbestand.'},
{id:'v07-12-09',field:12,topic:'Wirtschaftlichkeit',difficulty:3,type:'free',question:'Ein Lager senkt seinen durchschnittlichen Bestand stark. Nenne einen möglichen Vorteil und zwei mögliche Risiken.',keywords:['kapitalbindung','kosten','platz','fehlmenge','lieferbereitschaft','engpass','eilbeschaffung','risiko'],minHits:3,solution:'Vorteil können geringere Kapitalbindung und Lagerkosten sein. Risiken sind beispielsweise Fehlmengen, sinkende Lieferbereitschaft oder zusätzliche Eilbeschaffungskosten.'},
{id:'v07-12-10',field:12,topic:'Lagerkennzahlen',difficulty:2,type:'mc',question:'Welche Werte werden für den einfachen durchschnittlichen Lagerbestand benötigt?',options:['Anfangsbestand und Endbestand','Nur der Höchstbestand','Jahresumsatz und Gewinn','Lieferzeit und Mindestbestand'],correct:[0],solution:'Einfacher durchschnittlicher Lagerbestand = (Anfangsbestand + Endbestand) ÷ 2.'},
];
