// Kuratierter Zusatzpool: abwechslungsreiche, praxisnahe Aufgaben ohne reine Begriffs-Dopplungen.
// 3 neue Qualitätsfragen je Lernfeld. Der bestehende Pool bleibt erhalten, damit Lernhistorien-IDs stabil bleiben.
export const qualityQuestions = [
// LF1 Waren annehmen
{id:'q10-1-01',field:1,topic:'Warenannahme',difficulty:3,type:'free',question:'Der Fahrer möchte sofort weiterfahren, obwohl die Anzahl der Packstücke noch nicht geprüft wurde. Wie gehst du vor und warum?',keywords:['prüfen','packstücke','menge','quittieren','bestätigen','vorbehalt','frachtführer'],minHits:3,solution:'Vor einer vorbehaltlosen Bestätigung werden die äußerlich erkennbaren Angaben geprüft, insbesondere Empfänger, Anzahl der Packstücke und erkennbare Schäden. Abweichungen werden dokumentiert und bei der Empfangsbestätigung vermerkt.'},
{id:'q10-1-02',field:1,topic:'Mängel',difficulty:3,type:'mc',question:'Bei der Anlieferung ist ein Karton deutlich eingedrückt. Welche Schritte sind sinnvoll?',options:['Schaden dokumentieren','Schaden bei der Annahme vermerken','Ware ungeprüft einlagern und nichts notieren','Inhalt nach betrieblichem Ablauf prüfen'],correct:[0,1,3],solution:'Ein äußerlich erkennbarer Schaden sollte dokumentiert und bei der Annahme vermerkt werden. Anschließend wird die Ware nach dem betrieblichen Prüfablauf behandelt.'},
{id:'q10-1-03',field:1,topic:'Dokumente',difficulty:2,type:'free',question:'Warum sollten Bestellung, Lieferschein und tatsächlich gelieferte Ware miteinander abgeglichen werden?',keywords:['artikel','menge','bestellung','abweichung','lieferung','kontrolle'],minHits:3,solution:'Der Abgleich zeigt, ob die bestellten Artikel und Mengen tatsächlich geliefert wurden und macht Abweichungen frühzeitig sichtbar.'},
// LF2 Güter lagern
{id:'q10-2-01',field:2,topic:'Lagerarten',difficulty:3,type:'mc',question:'Ein Betrieb lagert sehr schwere Palettenware mit geringer Artikelvielfalt. Welches Kriterium ist bei der Wahl des Lagersystems besonders wichtig?',options:['Tragfähigkeit und sichere Handhabung','Farbe der Regale','Name des Lieferanten','Anzahl der Büroarbeitsplätze'],correct:[0],solution:'Bei schwerer Palettenware müssen insbesondere Tragfähigkeit, Abmessungen, Zugriff und sichere Handhabung zum Lagergut passen.'},
{id:'q10-2-02',field:2,topic:'Bestände',difficulty:3,type:'free',question:'Nenne zwei Nachteile eines unnötig hohen Lagerbestands und zwei mögliche Vorteile eines ausreichenden Sicherheitsbestands.',keywords:['kapitalbindung','lagerkosten','platz','risiko','lieferfähigkeit','fehlmenge','sicherheit'],minHits:4,solution:'Hohe Bestände erhöhen z. B. Kapitalbindung, Lagerkosten, Platzbedarf und Bestandsrisiken. Ein angemessener Sicherheitsbestand kann dagegen Lieferbereitschaft erhöhen und Fehlmengen bei Schwankungen abfedern.'},
{id:'q10-2-03',field:2,topic:'Lagerkennzahlen',difficulty:3,type:'mc',question:'Der durchschnittliche Lagerbestand sinkt bei unverändertem Jahresverbrauch. Was passiert grundsätzlich mit der Umschlagshäufigkeit?',options:['Sie steigt','Sie sinkt','Sie bleibt zwingend gleich','Sie wird immer null'],correct:[0],solution:'Umschlagshäufigkeit = Jahresverbrauch bzw. Wareneinsatz / durchschnittlicher Lagerbestand. Sinkt der Nenner bei gleichem Verbrauch, steigt die Umschlagshäufigkeit.'},
// LF3 Güter bearbeiten
{id:'q10-3-01',field:3,topic:'VAS',difficulty:3,type:'free',question:'Ein Kunde verlangt vor dem Versand eine kundenspezifische Etikettierung und Set-Bildung. Warum zählen diese Tätigkeiten zu Value Added Services?',keywords:['zusatzleistung','kunde','wert','etikett','set','dienstleistung'],minHits:3,solution:'Es handelt sich um zusätzliche logistische Dienstleistungen, die über reine Lagerung und Transport hinausgehen und einen kundenspezifischen Mehrwert schaffen.'},
{id:'q10-3-02',field:3,topic:'Kontrolle',difficulty:2,type:'mc',question:'Warum ist nach einer Bearbeitung der Ware eine Endkontrolle sinnvoll?',options:['Um Bearbeitungsfehler vor der Weitergabe zu erkennen','Damit grundsätzlich mehr Bestand entsteht','Um die Lieferadresse zu löschen','Damit keine Dokumentation nötig ist'],correct:[0],solution:'Die Endkontrolle soll sicherstellen, dass die Bearbeitung korrekt ausgeführt wurde und fehlerhafte Ware nicht in den Folgeprozess gelangt.'},
{id:'q10-3-03',field:3,topic:'Kennzeichnung',difficulty:3,type:'free',question:'Welche Folgen kann eine falsche Artikelkennzeichnung nach dem Umpacken haben? Nenne drei.',keywords:['verwechslung','fehlkommissionierung','fehlbestand','rückverfolgung','kunde','reklamation','falsch'],minHits:3,solution:'Mögliche Folgen sind Verwechslungen, Fehlkommissionierungen, falsche Bestände, Probleme bei der Rückverfolgbarkeit und Reklamationen.'},
// LF4 Güter im Betrieb transportieren
{id:'q10-4-01',field:4,topic:'Flurförderzeuge',difficulty:3,type:'mc',question:'Welche Faktoren müssen bei der Auswahl eines Flurförderzeugs zusammen betrachtet werden?',options:['Gewicht und Abmessungen der Last','Fahrwege und Bodenverhältnisse','Erforderliche Hubhöhe','Lieblingsmarke des Fahrers'],correct:[0,1,2],solution:'Tragfähigkeit, Lastabmessungen, Hubhöhe sowie Fahrwege und Einsatzbedingungen müssen zum Transportauftrag passen.'},
{id:'q10-4-02',field:4,topic:'Sicherheit',difficulty:3,type:'free',question:'Warum ist eine hoch angehobene Last beim Fahren eines Staplers problematisch?',keywords:['schwerpunkt','stabilität','kippen','sicht','last','niedrig'],minHits:3,solution:'Eine hoch angehobene Last verschlechtert Stabilität und Sicht und erhöht die Kippgefahr. Beim Fahren wird die Last grundsätzlich möglichst niedrig und sicher geführt.'},
{id:'q10-4-03',field:4,topic:'Transportwege',difficulty:2,type:'mc',question:'Welche Maßnahme reduziert Konflikte zwischen Fußgängern und Flurförderzeugen besonders?',options:['Klare Verkehrswege und gekennzeichnete Bereiche','Unübersichtliche Kreuzungen schaffen','Warnzeichen entfernen','Fahrwege als Abstellfläche nutzen'],correct:[0],solution:'Klare Verkehrswege, Markierungen, Sichtbeziehungen und betriebliche Verkehrsregeln reduzieren das Unfallrisiko.'},
// LF5 Kommissionieren
{id:'q10-5-01',field:5,topic:'Kommissionierverfahren',difficulty:3,type:'free',question:'Wann kann zweistufiges Kommissionieren gegenüber der auftragsweisen Kommissionierung vorteilhaft sein?',keywords:['mehrere aufträge','gesamtmenge','bündeln','sortieren','verteilen','wege','leistung'],minHits:3,solution:'Bei vielen ähnlichen Aufträgen können Artikel zunächst für mehrere Aufträge gebündelt entnommen und anschließend verteilt werden. Dadurch lassen sich Wege reduzieren und Leistungen erhöhen.'},
{id:'q10-5-02',field:5,topic:'Fehler',difficulty:3,type:'mc',question:'Ein Scanner bestätigt den richtigen Artikel, der Mitarbeiter entnimmt aber 8 statt 6 Stück. Welche Fehlerart liegt vor?',options:['Mengenfehler','Artfehler','Auslassungsfehler','Adressfehler'],correct:[0],solution:'Der Artikel stimmt, aber die entnommene Menge ist falsch. Das ist ein Mengenfehler.'},
{id:'q10-5-03',field:5,topic:'Kommissionierleistung',difficulty:3,type:'free',question:'Nenne drei Möglichkeiten, die Kommissionierleistung zu erhöhen, ohne die Fehlerquote bewusst in Kauf zu nehmen.',keywords:['wege','lagerplatz','scanner','pick by','schulung','ergonomie','nachschub','organisation'],minHits:3,solution:'Möglichkeiten sind z. B. Wegoptimierung, geeignete Lagerplatzorganisation, technische Assistenzsysteme, rechtzeitiger Nachschub und ergonomische Arbeitsplätze.'},
// LF6 Verpacken
{id:'q10-6-01',field:6,topic:'Packmittel',difficulty:3,type:'mc',question:'Ein empfindliches Produkt füllt den Karton nur zur Hälfte. Was ist sinnvoll?',options:['Passenderen Karton wählen oder Hohlräume sicher ausfüllen','Produkt lose im Karton bewegen lassen','Karton offen versenden','Kennzeichnungen grundsätzlich weglassen'],correct:[0],solution:'Die Verpackung sollte zum Packgut passen. Unnötige Hohlräume erhöhen Bewegungen und Schadensrisiken und sollten vermieden oder fachgerecht ausgefüllt werden.'},
{id:'q10-6-02',field:6,topic:'Verpackungsfunktionen',difficulty:3,type:'free',question:'Warum kann eine kleinere, passende Verpackung gleichzeitig Kosten und Umweltbelastung senken?',keywords:['material','füllmaterial','volumen','transport','platz','kosten','abfall'],minHits:3,solution:'Eine passende Verpackung benötigt häufig weniger Pack- und Füllmaterial, verursacht weniger Abfall und kann Transport- und Lagerraum besser ausnutzen.'},
{id:'q10-6-03',field:6,topic:'Kennzeichnung',difficulty:3,type:'mc',question:'Warum darf ein Handhabungszeichen allein eine ungeeignete Verpackung nicht ersetzen?',options:['Die Verpackung muss das Gut selbst ausreichend schützen','Kennzeichnungen machen Kartons wasserdicht','Jedes Zeichen erhöht automatisch die Tragfähigkeit','Ein Aufkleber ersetzt Polstermaterial immer'],correct:[0],solution:'Handhabungszeichen geben Hinweise, ersetzen aber keine für die Belastungen geeignete und ausreichend schützende Verpackung.'},
// LF7 Touren planen
{id:'q10-7-01',field:7,topic:'Fahrzeuge',difficulty:3,type:'free',question:'Ein Lkw hat 2 t Nutzlast frei, aber keinen ausreichenden Laderaum mehr. Warum kann die zusätzliche Ware trotzdem nicht mit?',keywords:['volumen','laderaum','platz','nutzlast','beide','grenze'],minHits:2,solution:'Bei der Fahrzeugauswahl begrenzen sowohl Nutzlast als auch Ladevolumen. Freie Gewichtskapazität nützt nichts, wenn die Ware räumlich nicht mehr sicher aufgenommen werden kann.'},
{id:'q10-7-02',field:7,topic:'Tourenplanung',difficulty:3,type:'mc',question:'Zwei Kunden haben enge Zeitfenster. Welche Planung ist am sinnvollsten?',options:['Zeitfenster gemeinsam mit Fahrzeit, Strecke und Verkehr berücksichtigen','Nur nach Luftlinie sortieren','Zeitfenster ignorieren','Immer alphabetisch fahren'],correct:[0],solution:'Eine realistische Tour berücksichtigt Zeitfenster zusammen mit Fahrzeiten, Strecken, Verkehr und weiteren Randbedingungen.'},
{id:'q10-7-03',field:7,topic:'Wirtschaftlichkeit',difficulty:3,type:'free',question:'Warum kann die kürzeste Strecke trotzdem nicht die wirtschaftlichste Tour sein?',keywords:['zeit','verkehr','maut','zeitfenster','kosten','fahrzeit','route'],minHits:3,solution:'Die kürzeste Entfernung kann durch Stau, Fahrzeit, Maut, Zeitfenster oder ungeeignete Straßen höhere Gesamtkosten verursachen. Entscheidend ist die wirtschaftliche Gesamtroute.'},
// LF8 Verladen
{id:'q10-8-01',field:8,topic:'Ladungssicherung',difficulty:3,type:'mc',question:'Was ist beim Niederzurren der zentrale Wirkmechanismus?',options:['Die Anpresskraft und damit die Reibung wird erhöht','Die Ladung wird leichter','Die Fahrzeugnutzlast steigt','Reibung wird vollständig beseitigt'],correct:[0],solution:'Niederzurren erhöht über die Vorspannkraft die Anpresskraft und damit die sichernde Reibung zwischen Ladung und Ladefläche.'},
{id:'q10-8-02',field:8,topic:'Lastverteilung',difficulty:3,type:'free',question:'Warum reicht es nicht, nur das zulässige Gesamtgewicht des Fahrzeugs einzuhalten?',keywords:['achslast','verteilung','schwerpunkt','fahrverhalten','zulässig'],minHits:2,solution:'Zusätzlich müssen zulässige Achslasten und eine sichere Lastverteilung eingehalten werden. Eine ungünstige Verteilung kann Fahrverhalten und Stabilität beeinträchtigen.'},
{id:'q10-8-03',field:8,topic:'Ladungssicherung',difficulty:3,type:'mc',question:'Welche Aussage zu Antirutschmatten ist richtig?',options:['Sie können den Reibbeiwert erhöhen, ersetzen aber nicht automatisch jede weitere Sicherung','Sie machen jede Ladung unabhängig von Gewicht und Aufbau sicher','Sie verringern grundsätzlich die Reibung','Sie dürfen nur unter leeren Paletten verwendet werden'],correct:[0],solution:'Antirutschmatten können die Reibung erhöhen. Welche zusätzliche Sicherung erforderlich ist, hängt von Ladung, Reibwert und Sicherungsverfahren ab.'},
// LF9 Versenden
{id:'q10-9-01',field:9,topic:'Versandarten',difficulty:3,type:'free',question:'Eine Sendung ist klein, sehr wertvoll und muss morgen sicher beim Kunden sein. Welche Kriterien sind bei der Versandwahl besonders wichtig?',keywords:['laufzeit','tracking','versicherung','wert','zustellung','zuverlässigkeit','kosten'],minHits:4,solution:'Neben der Laufzeit sind insbesondere Zuverlässigkeit, Sendungsverfolgung, Haftungs-/Versicherungsbedingungen, sichere Zustellung und Kosten zu prüfen.'},
{id:'q10-9-02',field:9,topic:'Frachtpapiere',difficulty:3,type:'mc',question:'Welche Folge kann ein falsches Sendungsgewicht haben?',options:['Falsche Kostenberechnung und Probleme bei der Transportabwicklung','Automatisch bessere Verpackung','Der Empfänger wird immer korrekt erkannt','Keine, Gewicht ist für Transporte bedeutungslos'],correct:[0],solution:'Gewicht kann für Preis, Fahrzeug- und Transportplanung sowie zulässige Grenzen relevant sein. Falsche Angaben können daher Kosten und Ablauf verfälschen.'},
{id:'q10-9-03',field:9,topic:'KEP',difficulty:3,type:'free',question:'Worin unterscheiden sich Express- und Standardversand aus Kundensicht typischerweise?',keywords:['laufzeit','termin','schnell','preis','kosten','zustellung'],minHits:3,solution:'Expressprodukte bieten typischerweise kürzere oder zugesagte Laufzeiten bzw. Zustelltermine, sind dafür in der Regel teurer als Standardversand.'},
// LF10 Logistische Prozesse optimieren
{id:'q10-10-01',field:10,topic:'KVP',difficulty:3,type:'mc',question:'Nach einer Prozessänderung sinkt die Durchlaufzeit, aber Reklamationen steigen deutlich. Wie ist das Ergebnis zu bewerten?',options:['Die Verbesserung muss anhand mehrerer Ziele geprüft und ggf. angepasst werden','Die Maßnahme ist automatisch erfolgreich','Qualität spielt bei KVP keine Rolle','Nur die schnellere Zeit zählt'],correct:[0],solution:'Prozessverbesserung betrachtet nicht nur Geschwindigkeit. Steigende Qualitätsprobleme zeigen einen Zielkonflikt und erfordern Analyse und Anpassung.'},
{id:'q10-10-02',field:10,topic:'Lean',difficulty:3,type:'free',question:'Ein Mitarbeiter läuft pro Auftrag mehrfach zum weit entfernten Drucker. Welche Lean-Verschwendung erkennst du und wie könnte man sie reduzieren?',keywords:['bewegung','wege','drucker','arbeitsplatz','layout','unnötig'],minHits:3,solution:'Die unnötigen Laufwege sind Verschwendung durch Bewegung. Ein günstigeres Layout, ein näherer Drucker oder ein digitalisierter Ablauf kann die Wege reduzieren.'},
{id:'q10-10-03',field:10,topic:'Qualität',difficulty:3,type:'mc',question:'Warum ist eine Fehlerquote allein noch keine Ursachenanalyse?',options:['Sie zeigt das Ausmaß, aber nicht automatisch die Ursache der Fehler','Sie nennt immer direkt den verantwortlichen Mitarbeiter','Sie ersetzt jede Prozessbeobachtung','Sie macht weitere Daten unnötig'],correct:[0],solution:'Eine Kennzahl beschreibt zunächst das Ergebnis. Für Ursachen müssen Prozess, Fehlerarten und Einflussfaktoren weiter untersucht werden.'},
// LF11 Beschaffung
{id:'q10-11-01',field:11,topic:'Lieferanten',difficulty:3,type:'mc',question:'Lieferant A ist 3 % günstiger, liefert aber häufig verspätet. Welche Aussage ist richtig?',options:['Der niedrigste Preis allein reicht für eine wirtschaftliche Lieferantenentscheidung nicht aus','A muss immer gewählt werden','Termintreue hat niemals wirtschaftliche Folgen','Nur der Listenpreis darf verglichen werden'],correct:[0],solution:'Neben dem Preis können Termintreue, Qualität, Lieferzeit, Service und Folgekosten entscheidend für die wirtschaftlichste Beschaffung sein.'},
{id:'q10-11-02',field:11,topic:'Bestellverfahren',difficulty:3,type:'free',question:'Warum kann eine längere Lieferzeit einen höheren Meldebestand erforderlich machen?',keywords:['lieferzeit','verbrauch','bedarf','mindestbestand','überbrücken','fehlmenge'],minHits:3,solution:'Während einer längeren Lieferzeit muss mehr Verbrauch überbrückt werden. Bei gleichem Verbrauch und Mindestbestand steigt daher grundsätzlich der Meldebestand.'},
{id:'q10-11-03',field:11,topic:'Beschaffung',difficulty:3,type:'mc',question:'Ein Mengenrabatt senkt den Einkaufspreis, verdoppelt aber den durchschnittlichen Bestand. Was muss zusätzlich bewertet werden?',options:['Zusätzliche Lager- und Kapitalbindungskosten','Nur die Farbe der Verpackung','Privatkosten des Einkäufers','Nichts, Rabatt ist immer wirtschaftlicher'],correct:[0],solution:'Ein niedrigerer Einstandspreis kann durch höhere Lagerhaltung, Kapitalbindung und Bestandsrisiken teilweise oder vollständig aufgezehrt werden.'},
// LF12 Kennzahlen/Wirtschaftlichkeit
{id:'q10-12-01',field:12,topic:'Lagerkennzahlen',difficulty:3,type:'free',question:'Die Umschlagshäufigkeit steigt von 4 auf 8, während der Jahresverbrauch gleich bleibt. Was lässt sich über den durchschnittlichen Lagerbestand sagen?',keywords:['sinkt','halbiert','durchschnitt','bestand','umschlag'],minHits:2,solution:'Bei unverändertem Jahresverbrauch ist der durchschnittliche Lagerbestand umgekehrt proportional zur Umschlagshäufigkeit. Verdoppelt sich der Umschlag von 4 auf 8, halbiert sich der durchschnittliche Bestand.'},
{id:'q10-12-02',field:12,topic:'Kosten',difficulty:3,type:'mc',question:'Welche Kostenart gehört typischerweise zu den Lagerhaltungskosten?',options:['Kapitalbindungskosten des Bestands','Einkaufspreis jeder verkauften Ware als solcher','Privater Arbeitsweg des Kunden','Umsatzsteuer des Endkunden'],correct:[0],solution:'Zum Vorhalten von Lagerbeständen gehören unter anderem Raum-, Personal-, Versicherungs-, Risiko- und Kapitalbindungskosten.'},
{id:'q10-12-03',field:12,topic:'Wirtschaftlichkeit',difficulty:3,type:'free',question:'Warum sollte eine einzelne Lagerkennzahl nicht isoliert optimiert werden?',keywords:['zielkonflikt','kosten','service','qualität','bestand','kennzahlen','auswirkung'],minHits:3,solution:'Kennzahlen beeinflussen sich gegenseitig. Ein sehr niedriger Bestand kann z. B. Lagerkosten senken, aber Fehlmengen und schlechtere Lieferbereitschaft verursachen. Deshalb müssen Zielkonflikte gemeinsam bewertet werden.'}
];
