// Ersatzpool LF 1–4: 7 zusätzliche Transferfragen je Lernfeld.
// Zusammen mit v05 (15) + quality (3) ergeben sich 25 kuratierte Aufgaben je LF 1–4.
export const v11Questions = [
// LF1
{id:'v11-1-01',field:1,topic:'Warenannahme',difficulty:2,type:'mc',question:'Eine Lieferung kommt ohne angekündigten Lieferschein an. Was ist die beste erste Reaktion?',options:['Lieferung eindeutig zuordnen und weiteres Vorgehen nach betrieblicher Vorgabe klären','Ware ungeprüft irgendwo abstellen','Selbst einen Lieferschein erfinden','Sendung automatisch vernichten'],correct:[0],solution:'Fehlende Unterlagen sind zu klären. Die Lieferung muss eindeutig zugeordnet und nach betrieblichem Ablauf behandelt werden.'},
{id:'v11-1-02',field:1,topic:'Mängel',difficulty:3,type:'free',question:'Bei einer Lieferung sind Verpackung und Ware nass. Nenne drei Dinge, die du vor der Einlagerung veranlassen solltest.',keywords:['dokumentieren','foto','prüfen','fahrer','frachtführer','melden','separieren','quarantäne'],minHits:3,solution:'Schaden dokumentieren bzw. fotografieren, Zustand und Umfang prüfen, Fahrer/Frachtführer bzw. zuständige Stelle informieren und betroffene Ware bis zur Klärung gegebenenfalls separieren.'},
{id:'v11-1-03',field:1,topic:'Begleitpapiere',difficulty:2,type:'mc',question:'Warum ist die Bestellnummer beim Wareneingang hilfreich?',options:['Sie erleichtert die Zuordnung der Lieferung zum Beschaffungsvorgang','Sie ersetzt die Artikelnummer auf jedem Produkt','Sie bestimmt die Staplergeschwindigkeit','Sie ist nur für den Fahrer privat relevant'],correct:[0],solution:'Die Bestellnummer verbindet die Lieferung mit dem zugrunde liegenden Beschaffungsvorgang und erleichtert den Soll-Ist-Abgleich.'},
{id:'v11-1-04',field:1,topic:'Warenannahme',difficulty:3,type:'free',question:'Eine Lieferung enthält den richtigen Artikel, aber eine andere als die bestellte Menge. Welche Informationen sollten dokumentiert werden?',keywords:['soll','ist','menge','artikel','lieferschein','abweichung','datum','lieferung'],minHits:3,solution:'Dokumentiert werden sollten mindestens betroffener Artikel, Soll- und Ist-Menge sowie die Zuordnung zur Lieferung bzw. zu den Lieferpapieren. Weitere betriebliche Angaben können ergänzt werden.'},
{id:'v11-1-05',field:1,topic:'Mängel',difficulty:3,type:'mc',question:'Eine Ware ist äußerlich einwandfrei, entspricht aber nach Prüfung nicht der vereinbarten Qualität. Was liegt nahe?',options:['Ein Sach- bzw. Qualitätsmangel','Automatisch ein Mengenmangel','Kein Mangel, weil die Verpackung heil ist','Nur ein Lagerplatzfehler'],correct:[0],solution:'Entspricht die Beschaffenheit nicht der vereinbarten Qualität, liegt ein Sach- bzw. Qualitätsmangel nahe.'},
{id:'v11-1-06',field:1,topic:'Warenannahme',difficulty:2,type:'mc',question:'Warum kann eine Wareneingangszone sinnvoll sein?',options:['Sie schafft einen definierten Bereich für Kontrolle und Klärung vor der Einlagerung','Sie ersetzt jede Bestandsbuchung','Dort muss jede Ware dauerhaft bleiben','Sie dient ausschließlich als Pausenraum'],correct:[0],solution:'In der Wareneingangszone können Lieferungen geordnet angenommen, geprüft, gebucht und bei Abweichungen geklärt werden.'},
{id:'v11-1-07',field:1,topic:'Begleitpapiere',difficulty:3,type:'free',question:'Warum sollte eine festgestellte Abweichung möglichst eindeutig statt nur mit „stimmt nicht“ dokumentiert werden?',keywords:['nachweis','konkret','menge','artikel','schaden','klärung','reklamation'],minHits:2,solution:'Eine konkrete Beschreibung macht Art und Umfang der Abweichung nachvollziehbar und erleichtert Klärung, Nachweis und Reklamation.'},
// LF2
{id:'v11-2-01',field:2,topic:'Lagerarten',difficulty:3,type:'mc',question:'Welcher Vorteil spricht bei vielen verschiedenen Palettenartikeln häufig für ein Palettenregal gegenüber reiner Blocklagerung?',options:['Direkterer Zugriff auf einzelne Ladeeinheiten','Es benötigt grundsätzlich keine Verkehrswege','Jede Ware kann unbegrenzt gestapelt werden','Bestandsführung wird überflüssig'],correct:[0],solution:'Palettenregale ermöglichen in der Regel direkten Zugriff auf einzelne Ladeeinheiten und eignen sich daher gut bei größerer Artikelvielfalt.'},
{id:'v11-2-02',field:2,topic:'Bestände',difficulty:3,type:'free',question:'Der Verbrauch schwankt stark, die Lieferzeit ist ebenfalls unsicher. Welche Bestandsgröße dient besonders als Puffer und warum?',keywords:['mindestbestand','sicherheitsbestand','puffer','schwankung','lieferzeit','fehlmenge'],minHits:3,solution:'Der Mindest- bzw. Sicherheitsbestand dient als Puffer gegen unerwarteten Mehrverbrauch und Lieferverzögerungen und reduziert das Fehlmengenrisiko.'},
{id:'v11-2-03',field:2,topic:'Lagerkennzahlen',difficulty:3,type:'mc',question:'Welche Aussage zur durchschnittlichen Lagerdauer ist richtig?',options:['Sie beschreibt, wie lange Ware im Durchschnitt im Lager gebunden ist','Sie ist identisch mit der Lieferzeit des Lieferanten','Sie gibt nur die Regalhöhe an','Sie kann nie aus der Umschlagshäufigkeit abgeleitet werden'],correct:[0],solution:'Die durchschnittliche Lagerdauer beschreibt die mittlere Verweildauer des Bestands. Häufig gilt bei 360 Tagen: Lagerdauer = 360 ÷ Umschlagshäufigkeit.'},
{id:'v11-2-04',field:2,topic:'Lagerarten',difficulty:2,type:'free',question:'Warum benötigt chaotische Lagerplatzordnung besonders zuverlässige Buchungen?',keywords:['lagerplatz','system','finden','bestand','buchung','wms','zuordnung'],minHits:3,solution:'Da ein Artikel keinen dauerhaft festen Platz hat, muss das System die aktuelle Lagerplatzzuordnung korrekt kennen. Fehlbuchungen können sonst dazu führen, dass Bestand praktisch nicht auffindbar ist.'},
{id:'v11-2-05',field:2,topic:'Bestände',difficulty:3,type:'mc',question:'Welche Folge kann ein zu hoch festgelegter Mindestbestand haben?',options:['Unnötig hohe Kapitalbindung und Lagerkosten','Automatisch kürzere Lieferzeit','Immer weniger Lagerfläche','Bestellungen werden grundsätzlich kostenlos'],correct:[0],solution:'Ein überhöhter Sicherheitsbestand bindet unnötig Kapital und Lagerfläche und kann Lagerkosten sowie Bestandsrisiken erhöhen.'},
{id:'v11-2-06',field:2,topic:'Lagerkennzahlen',difficulty:3,type:'free',question:'Nenne zwei mögliche Ursachen für eine ungewöhnlich niedrige Umschlagshäufigkeit eines Artikels.',keywords:['überbestand','absatz','verbrauch','langsam','bedarf','einkauf','bestand'],minHits:2,solution:'Mögliche Ursachen sind ein zu hoher Bestand bzw. zu große Beschaffungsmengen oder ein gesunkener Verbrauch/Absatz. Auch Sortimentsänderungen können eine Rolle spielen.'},
{id:'v11-2-07',field:2,topic:'Lagerarten',difficulty:3,type:'mc',question:'Bei welcher Ware ist FEFO gegenüber reinem FIFO besonders sinnvoll?',options:['Ware mit unterschiedlichen Verfallsdaten','Stahlteilen ohne Haltbarkeitsbezug','Leeren Mehrwegpaletten','Büromöbeln ohne Datumsbezug'],correct:[0],solution:'Bei Ware mit Verfallsdaten sollte das früheste Ablaufdatum berücksichtigt werden. FEFO steht für First Expired, First Out.'},
// LF3
{id:'v11-3-01',field:3,topic:'Kennzeichnung',difficulty:3,type:'mc',question:'Ein Etikett ist korrekt gedruckt, wird aber auf den falschen Artikel geklebt. Welches Hauptproblem entsteht?',options:['Die eindeutige Identifikation und Rückverfolgbarkeit wird verfälscht','Der Artikel wird automatisch leichter','Die Lagerfläche vergrößert sich','Die Lieferzeit des Herstellers sinkt'],correct:[0],solution:'Eine falsche Zuordnung kann Identifikation, Bestandsführung, Kommissionierung und Rückverfolgbarkeit verfälschen.'},
{id:'v11-3-02',field:3,topic:'Mehrwertleistungen',difficulty:2,type:'free',question:'Nenne drei Beispiele für kundenspezifische Bearbeitungen, die ein Logistikdienstleister zusätzlich übernehmen kann.',keywords:['etikettieren','konfektionieren','set','display','montage','umpacken','qualitätskontrolle'],minHits:3,solution:'Beispiele sind Etikettieren, Konfektionieren bzw. Set-Bildung, Umpacken, Displaybau, Qualitätskontrollen oder einfache Montagearbeiten.'},
{id:'v11-3-03',field:3,topic:'Verpackung',difficulty:3,type:'mc',question:'Nach einer Qualitätskontrolle wird Ware neu verpackt. Was muss vor der Weitergabe besonders sichergestellt werden?',options:['Ware, Menge und Kennzeichnung müssen wieder eindeutig zusammenpassen','Die alte Verpackung muss zwingend weiterverwendet werden','Jede Kennzeichnung wird entfernt','Der Bestand darf nicht gebucht werden'],correct:[0],solution:'Nach der Bearbeitung müssen Identität, Menge, Zustand und erforderliche Kennzeichnungen korrekt sein.'},
{id:'v11-3-04',field:3,topic:'Kennzeichnung',difficulty:3,type:'free',question:'Warum ist eine Seriennummer bei bestimmten Produkten für die Rückverfolgbarkeit genauer als nur die Artikelnummer?',keywords:['einzelstück','individuell','gerät','zuordnung','rückverfolgung','artikelnummer'],minHits:2,solution:'Die Artikelnummer bezeichnet meist eine Produktart, während eine Seriennummer ein konkretes Einzelstück eindeutig identifizieren kann.'},
{id:'v11-3-05',field:3,topic:'Mehrwertleistungen',difficulty:3,type:'mc',question:'Welches Ziel hat eine dokumentierte Endkontrolle nach einer kundenspezifischen Bearbeitung?',options:['Nachweisen, dass die geforderten Arbeitsschritte und Qualitätsmerkmale geprüft wurden','Die Bearbeitung rückgängig machen','Den Kundenauftrag löschen','Die Ware automatisch verkaufen'],correct:[0],solution:'Die Endkontrolle soll Fehler vor der Weitergabe erkennen und die ordnungsgemäße Ausführung nachvollziehbar machen.'},
{id:'v11-3-06',field:3,topic:'Verpackung',difficulty:2,type:'free',question:'Nenne drei Gründe, warum Ware vor dem Versand umgepackt werden kann.',keywords:['schutz','kunde','beschädigt','größe','transport','kennzeichnung','set','verkauf'],minHits:3,solution:'Gründe können beschädigte oder ungeeignete Verpackung, besserer Transportschutz, kundenspezifische Verpackung, Set-Bildung oder eine andere Verkaufs- bzw. Versandgröße sein.'},
{id:'v11-3-07',field:3,topic:'Kennzeichnung',difficulty:3,type:'mc',question:'Welcher Vorteil entsteht durch einen Scan unmittelbar nach einer Bearbeitung?',options:['Artikel und Bearbeitungsschritt können systemseitig eindeutig bestätigt werden','Die Ware benötigt keine physische Kontrolle mehr','Jeder Scan repariert beschädigte Ware','Der Scanner ersetzt sämtliche Kennzeichnungen'],correct:[0],solution:'Ein Scan kann die korrekte Artikelzuordnung und Prozessbuchung unterstützen, ersetzt aber nicht automatisch alle notwendigen Kontrollen.'},
// LF4
{id:'v11-4-01',field:4,topic:'Fördermittel',difficulty:3,type:'mc',question:'Für häufig wiederkehrende Transporte zwischen zwei festen Punkten kann welches System besonders geeignet sein?',options:['Rollenbahn oder Förderband','Beliebig wechselnder Handtransport über Treppen','Leiter','Bürostuhl'],correct:[0],solution:'Bei kontinuierlichen bzw. häufig wiederkehrenden Transporten auf einer festen Strecke können Stetigförderer wirtschaftlich sein.'},
{id:'v11-4-02',field:4,topic:'Sicherheit',difficulty:3,type:'free',question:'Ein Verkehrsweg ist durch abgestellte Paletten verengt. Warum sollte das vor dem Staplerverkehr behoben werden?',keywords:['fahrweg','sicht','abstand','kollision','unfall','sicherheit','palette'],minHits:3,solution:'Verengte oder blockierte Fahrwege reduzieren Sicherheitsabstände und Sicht und erhöhen Kollisions- und Unfallrisiken. Verkehrswege müssen entsprechend den betrieblichen Vorgaben freigehalten werden.'},
{id:'v11-4-03',field:4,topic:'Transportwege',difficulty:3,type:'mc',question:'Warum sind getrennte Fuß- und Fahrwege in stark befahrenen Lagerbereichen sinnvoll?',options:['Sie reduzieren Begegnungs- und Kollisionsrisiken','Sie erhöhen automatisch die Staplertragfähigkeit','Sie ersetzen jede Unterweisung','Sie machen Geschwindigkeitsregeln unnötig'],correct:[0],solution:'Eine räumliche Trennung reduziert gefährliche Begegnungen zwischen Personen und Flurförderzeugen.'},
{id:'v11-4-04',field:4,topic:'Fördermittel',difficulty:3,type:'free',question:'Nenne vier Kriterien für die Auswahl eines geeigneten innerbetrieblichen Fördermittels.',keywords:['gewicht','abmessung','strecke','hubhöhe','boden','häufigkeit','last','weg'],minHits:4,solution:'Wichtig sind z. B. Gewicht und Abmessungen der Last, Transportstrecke, erforderliche Hubhöhe, Boden- und Platzverhältnisse sowie Transporthäufigkeit.'},
{id:'v11-4-05',field:4,topic:'Sicherheit',difficulty:3,type:'mc',question:'Was ist bei einer unübersichtlichen Kreuzung im Lager besonders wichtig?',options:['Geschwindigkeit anpassen und betriebliche Vorfahrts-/Warnregeln beachten','Beschleunigen, um schneller durchzufahren','Nur auf die eigene Last schauen','Warnsignale grundsätzlich vermeiden'],correct:[0],solution:'An unübersichtlichen Stellen sind Geschwindigkeit, Sicht und betriebliche Verkehrsregeln besonders zu beachten.'},
{id:'v11-4-06',field:4,topic:'Transportwege',difficulty:2,type:'free',question:'Warum müssen Bodenbeschaffenheit und Tragfähigkeit bei Transportwegen berücksichtigt werden?',keywords:['gewicht','tragfähigkeit','stabilität','uneben','fahrzeug','last','sicherheit'],minHits:3,solution:'Boden und Verkehrsweg müssen Fahrzeug und Last sicher tragen. Unebenheiten oder unzureichende Tragfähigkeit können Stabilität, Bremsweg und Fahrsicherheit beeinträchtigen.'},
{id:'v11-4-07',field:4,topic:'Fördermittel',difficulty:3,type:'mc',question:'Welche Eigenschaft unterscheidet einen Gabelstapler grundsätzlich von einem reinen Handhubwagen?',options:['Ein Stapler kann Lasten motorisch transportieren und je nach Bauart auf größere Höhen heben','Ein Handhubwagen ist immer schneller','Nur Handhubwagen dürfen Paletten bewegen','Stapler benötigen grundsätzlich keine Tragfähigkeitsangabe'],correct:[0],solution:'Gabelstapler sind motorisierte Flurförderzeuge und können Lasten je nach Bauart auch auf größere Hubhöhen bewegen. Tragfähigkeitsgrenzen sind stets zu beachten.'}
];
