// v0.6: Ausbau Lernfelder 5–8 mit gemischten Freitext- und Multiple-Choice-Aufgaben.
export const v06Questions = [
// LF5 – Güter kommissionieren
{id:'v06-5-01',field:5,topic:'Kommissionierverfahren',difficulty:1,type:'mc',question:'Was beschreibt das Prinzip „Mann-zur-Ware“?',options:['Der Kommissionierer bewegt sich zum Lagerplatz','Die Ware fährt automatisch zum Kommissionierer','Nur Roboter dürfen kommissionieren','Die Ware wird direkt vom Lieferanten versendet'],correct:[0],solution:'Beim Mann-zur-Ware-Prinzip bewegt sich der Kommissionierer zum Lagerplatz und entnimmt dort die benötigte Ware.'},
{id:'v06-5-02',field:5,topic:'Kommissionierverfahren',difficulty:2,type:'mc',question:'Welche Vorteile kann das Prinzip „Ware-zum-Mann“ bieten?',options:['Kürzere Laufwege','Höherer Automatisierungsgrad','Jeder Lagerplatz muss manuell gesucht werden','Oft hohe Kommissionierleistung'],correct:[0,1,3],solution:'Ware-zum-Mann reduziert Wege, eignet sich gut für automatisierte Systeme und kann eine hohe Leistung ermöglichen.'},
{id:'v06-5-03',field:5,topic:'Fehler',difficulty:1,type:'mc',question:'Welcher Fall ist ein Mengenfehler beim Kommissionieren?',options:['5 Stück gefordert, 4 entnommen','Falscher Artikel entnommen','Ware beschädigt','Artikel komplett vergessen'],correct:[0],solution:'Ein Mengenfehler liegt vor, wenn vom richtigen Artikel die falsche Menge kommissioniert wird.'},
{id:'v06-5-04',field:5,topic:'Fehler',difficulty:2,type:'free',question:'Nenne vier typische Kommissionierfehler.',keywords:['mengenfehler','artfehler','falscher artikel','auslassungsfehler','zustandsfehler','beschädigt','falsche menge','verwechslung'],minHits:4,solution:'Typische Fehler sind Mengenfehler, Artfehler, Auslassungsfehler und Zustandsfehler, etwa beschädigte Ware.'},
{id:'v06-5-05',field:5,topic:'Kommissionierverfahren',difficulty:2,type:'free',question:'Erkläre den Unterschied zwischen ein- und zweistufiger Kommissionierung.',keywords:['auftrag','direkt','gesamtmenge','mehrere aufträge','sortieren','verteilen','zweite stufe'],minHits:3,solution:'Einstufig wird ein Auftrag direkt vollständig zusammengestellt. Zweistufig wird zunächst für mehrere Aufträge gesammelt und anschließend auf die einzelnen Aufträge verteilt.'},
{id:'v06-5-06',field:5,topic:'Belege',difficulty:1,type:'mc',question:'Welche Information ist auf einem Kommissionierbeleg besonders wichtig?',options:['Artikel und Menge','Privatadresse des Kommissionierers','Urlaubsplanung','Bilanzsumme'],correct:[0],solution:'Ein Kommissionierbeleg muss unter anderem Artikel und zu entnehmende Menge eindeutig ausweisen.'},
{id:'v06-5-07',field:5,topic:'Fehler',difficulty:2,type:'free',question:'Wie kannst du Kommissionierfehler durch technische Hilfsmittel reduzieren? Nenne drei Möglichkeiten.',keywords:['scanner','barcode','pick by voice','pick by light','kontrolle','wms','bestätigung'],minHits:3,solution:'Zum Beispiel Barcode-Scanner, Pick-by-Voice, Pick-by-Light oder systemgestützte Bestätigung im WMS.'},
{id:'v06-5-08',field:5,topic:'Kommissionierverfahren',difficulty:2,type:'mc',question:'Welche Aussagen zur wegoptimierten Kommissionierung sind richtig?',options:['Lagerplätze werden in sinnvoller Reihenfolge angelaufen','Unnötige Laufwege sollen reduziert werden','Die Reihenfolge der Lagerplätze ist egal','Sie kann die Kommissionierzeit senken'],correct:[0,1,3],solution:'Wegoptimierung ordnet Entnahmen so an, dass Lauf- bzw. Fahrwege möglichst kurz werden.'},
{id:'v06-5-09',field:5,topic:'Belege',difficulty:2,type:'free',question:'Warum ist eine eindeutige Lagerplatzangabe auf dem Kommissionierbeleg wichtig?',keywords:['lagerplatz','finden','verwechslung','schnell','weg','artikel'],minHits:2,solution:'Sie ermöglicht das schnelle Auffinden des richtigen Artikels und reduziert Verwechslungen und Suchzeiten.'},
{id:'v06-5-10',field:5,topic:'Fehler',difficulty:3,type:'mc',question:'Welche Maßnahme verbessert die Kommissionierqualität am ehesten?',options:['Jede Entnahme ohne Kontrolle bestätigen','Artikel per Scan mit Auftrag abgleichen','Lagerplätze bewusst ähnlich kennzeichnen','Fehler erst beim Kunden prüfen'],correct:[1],solution:'Der Scan-Abgleich zwischen Artikel und Auftrag reduziert Verwechslungen und Fehlentnahmen.'},

// LF6 – Güter verpacken
{id:'v06-6-01',field:6,topic:'Verpackungsfunktionen',difficulty:1,type:'mc',question:'Welche Funktionen kann eine Verpackung erfüllen?',options:['Schutzfunktion','Transportfunktion','Informationsfunktion','Lohnabrechnung'],correct:[0,1,2],solution:'Verpackungen schützen, erleichtern Transport und Lagerung und können wichtige Informationen tragen.'},
{id:'v06-6-02',field:6,topic:'Packmittel',difficulty:1,type:'mc',question:'Was ist ein Packmittel?',options:['Ein Behältnis, das das Packgut aufnimmt oder umschließt','Nur Klebeband','Ein Lieferschein','Ein Lagerplatz'],correct:[0],solution:'Ein Packmittel nimmt das Packgut auf oder umschließt es, zum Beispiel Karton, Kiste oder Fass.'},
{id:'v06-6-03',field:6,topic:'Packmittel',difficulty:2,type:'free',question:'Erkläre den Unterschied zwischen Packmittel und Packhilfsmittel und nenne je ein Beispiel.',keywords:['karton','kiste','behältnis','klebeband','folie','umreifung','packhilfsmittel'],minHits:3,solution:'Packmittel umschließen oder nehmen das Packgut auf, z. B. Karton. Packhilfsmittel unterstützen die Verpackung, z. B. Klebeband, Polster oder Umreifungsband.'},
{id:'v06-6-04',field:6,topic:'Verpackungsfunktionen',difficulty:2,type:'free',question:'Warum sollte eine Verpackung weder unnötig groß noch zu knapp gewählt werden?',keywords:['material','kosten','füllmaterial','schutz','bewegung','beschädigung','platz'],minHits:3,solution:'Zu große Verpackungen erhöhen Material-, Füll- und Transportaufwand. Zu kleine Verpackungen können Schutz und Stabilität beeinträchtigen.'},
{id:'v06-6-05',field:6,topic:'Kennzeichnung',difficulty:1,type:'mc',question:'Welches Kennzeichen weist auf zerbrechliche Ware hin?',options:['Symbol mit zerbrochenem Glas','Regenschirm','Pfeile nach oben','Gabelstapler-Symbol'],correct:[0],solution:'Das Symbol mit einem zerbrochenen Glas steht für zerbrechliche bzw. vorsichtig zu behandelnde Ware.'},
{id:'v06-6-06',field:6,topic:'Kennzeichnung',difficulty:2,type:'mc',question:'Welche Kennzeichnungen können auf Versandstücken sinnvoll sein?',options:['Oben-Pfeile','Vor Nässe schützen','Zerbrechlich','Private Handynummer des Packers'],correct:[0,1,2],solution:'Handhabungszeichen geben Hinweise für Transport und Lagerung, zum Beispiel oben, trocken halten oder zerbrechlich.'},
{id:'v06-6-07',field:6,topic:'Verpackungsfunktionen',difficulty:2,type:'free',question:'Nenne drei Anforderungen an eine transportgerechte Verpackung.',keywords:['schutz','stabil','belastung','stapeln','gewicht','feuchtigkeit','stoß','geeignet'],minHits:3,solution:'Sie muss zum Produkt passen, mechanischen und ggf. klimatischen Belastungen standhalten und ausreichend stabil für Transport und Umschlag sein.'},
{id:'v06-6-08',field:6,topic:'Packmittel',difficulty:2,type:'mc',question:'Wann ist Polstermaterial besonders sinnvoll?',options:['Wenn das Packgut stoßempfindlich ist','Wenn Hohlräume Bewegungen ermöglichen','Nur bei unzerbrechlicher Schüttware','Wenn Ware im Karton fixiert werden muss'],correct:[0,1,3],solution:'Polsterung schützt empfindliche Ware, füllt Hohlräume und verhindert unerwünschte Bewegung im Packstück.'},
{id:'v06-6-09',field:6,topic:'Kennzeichnung',difficulty:3,type:'free',question:'Warum müssen alte oder falsche Kennzeichnungen auf wiederverwendeten Verpackungen entfernt oder unkenntlich gemacht werden?',keywords:['verwechslung','falsch','gefahr','adresse','handhabung','kennzeichnung','fehlinformation'],minHits:2,solution:'Alte Kennzeichnungen können zu Fehlleitung, falscher Handhabung oder gefährlichen Missverständnissen führen und müssen daher entfernt oder eindeutig unkenntlich gemacht werden.'},
{id:'v06-6-10',field:6,topic:'Verpackungsfunktionen',difficulty:2,type:'mc',question:'Welche Folge kann eine mangelhafte Verpackung haben?',options:['Transportschäden','Höhere Reklamationsquote','Gefährdung beim Umschlag','Automatisch geringere Frachtkosten'],correct:[0,1,2],solution:'Ungeeignete Verpackung erhöht das Risiko von Schäden, Reklamationen und Gefährdungen beim Transport und Umschlag.'},

// LF7 – Touren planen
{id:'v06-7-01',field:7,topic:'Tourenplanung',difficulty:1,type:'mc',question:'Welche Faktoren sind bei der Tourenplanung wichtig?',options:['Liefertermine','Strecke','Fahrzeugkapazität','Lieblingsfarbe des Fahrers'],correct:[0,1,2],solution:'Tourenplanung berücksichtigt unter anderem Termine, Entfernungen und Fahrzeugkapazitäten.'},
{id:'v06-7-02',field:7,topic:'Fahrzeuge',difficulty:1,type:'mc',question:'Welche zwei Grenzen eines Fahrzeugs müssen besonders beachtet werden?',options:['Nutzlast','Ladevolumen','Radioleistung','Sitzbezug'],correct:[0,1],solution:'Entscheidend sind insbesondere zulässige Nutzlast und verfügbares Ladevolumen.'},
{id:'v06-7-03',field:7,topic:'Tourenplanung',difficulty:2,type:'free',question:'Nenne vier Ziele einer wirtschaftlichen Tourenplanung.',keywords:['wege','kilometer','zeit','auslastung','kosten','termine','leerfahrt','kunden'],minHits:4,solution:'Ziele sind z. B. kurze Wege und Fahrzeiten, hohe Auslastung, geringe Kosten und Leerfahrten sowie Einhaltung von Lieferterminen.'},
{id:'v06-7-04',field:7,topic:'Wirtschaftlichkeit',difficulty:2,type:'mc',question:'Welche Maßnahme kann die Wirtschaftlichkeit einer Tour verbessern?',options:['Leerfahrten reduzieren','Fahrzeuge möglichst schlecht auslasten','Lieferorte sinnvoll bündeln','Unnötige Umwege einplanen'],correct:[0,2],solution:'Wirtschaftlicher wird eine Tour durch hohe Auslastung, Bündelung und Vermeidung unnötiger Leer- oder Umwege.'},
{id:'v06-7-05',field:7,topic:'Fahrzeuge',difficulty:2,type:'free',question:'Warum reicht es bei der Fahrzeugauswahl nicht, nur auf das Ladevolumen zu achten?',keywords:['gewicht','nutzlast','achslast','zulässig','schwer','volumen'],minHits:2,solution:'Auch die zulässige Nutzlast und gegebenenfalls Achslasten begrenzen die Beladung. Ein Fahrzeug kann volumenmäßig noch Platz haben, aber gewichtsmäßig bereits ausgelastet sein.'},
{id:'v06-7-06',field:7,topic:'Tourenplanung',difficulty:2,type:'mc',question:'Was bedeutet eine Zeitfensterbelieferung?',options:['Der Kunde darf nur innerhalb eines festgelegten Zeitraums beliefert werden','Die Lieferung erfolgt irgendwann am Tag','Nur Nachtfahrten sind erlaubt','Das Fahrzeug darf nur 30 Minuten fahren'],correct:[0],solution:'Ein Zeitfenster gibt einen definierten Zeitraum vor, in dem die Lieferung erfolgen soll.'},
{id:'v06-7-07',field:7,topic:'Wirtschaftlichkeit',difficulty:3,type:'free',question:'Warum sind Leerfahrten wirtschaftlich ungünstig?',keywords:['kosten','kein ertrag','kraftstoff','zeit','fahrer','fahrzeug','auslastung'],minHits:3,solution:'Leerfahrten verursachen Fahrzeug-, Personal-, Zeit- und Energiekosten, ohne Transportleistung für einen Auftrag zu erbringen.'},
{id:'v06-7-08',field:7,topic:'Tourenplanung',difficulty:2,type:'mc',question:'Welche Reihenfolge ist bei mehreren Lieferstopps grundsätzlich sinnvoll?',options:['Eine möglichst kurze und terminverträgliche Route','Immer alphabetisch nach Kundennamen','Immer der entfernteste Kunde zuerst','Zufällige Reihenfolge'],correct:[0],solution:'Die Reihenfolge sollte Strecke, Zeitfenster, Verkehr und weitere Randbedingungen möglichst wirtschaftlich berücksichtigen.'},
{id:'v06-7-09',field:7,topic:'Fahrzeuge',difficulty:2,type:'mc',question:'Ein Fahrzeug hat noch viel Ladevolumen frei, ist aber bereits an der zulässigen Nutzlast. Darf weitere schwere Ware geladen werden?',options:['Nein','Ja, solange Platz vorhanden ist','Nur ohne Ladungssicherung','Immer bis das Volumen voll ist'],correct:[0],solution:'Die zulässige Nutzlast darf nicht überschritten werden, auch wenn noch Ladevolumen verfügbar ist.'},
{id:'v06-7-10',field:7,topic:'Wirtschaftlichkeit',difficulty:2,type:'free',question:'Nenne drei Kostenarten, die bei einer Tour berücksichtigt werden können.',keywords:['kraftstoff','personal','maut','fahrzeug','verschleiß','zeit','kosten'],minHits:3,solution:'Zum Beispiel Kraftstoff-/Energiekosten, Personalkosten, Maut, Fahrzeugkosten und Verschleiß.'},

// LF8 – Güter verladen
{id:'v06-8-01',field:8,topic:'Ladungssicherung',difficulty:1,type:'mc',question:'Was kennzeichnet formschlüssige Ladungssicherung?',options:['Ladung liegt lückenlos an Begrenzungen an','Nur Reibung hält die Ladung','Es wird grundsätzlich kein Sicherungsmittel benötigt','Die Ladung darf sich frei bewegen'],correct:[0],solution:'Formschluss verhindert Bewegung durch lückenloses Anlegen, Blockieren oder andere formschlüssige Sicherung.'},
{id:'v06-8-02',field:8,topic:'Ladungssicherung',difficulty:2,type:'mc',question:'Was wird beim Niederzurren hauptsächlich erhöht?',options:['Anpresskraft und damit Reibung','Ladevolumen','Nutzlast des Fahrzeugs','Geschwindigkeit'],correct:[0],solution:'Beim Niederzurren erhöht die Vorspannkraft die Anpresskraft und dadurch die Reibung zwischen Ladung und Ladefläche.'},
{id:'v06-8-03',field:8,topic:'Lastverteilung',difficulty:2,type:'free',question:'Warum ist die Lastverteilung beim Beladen eines Lkw wichtig?',keywords:['achslast','fahrverhalten','bremsen','lenken','sicherheit','gesamtgewicht','überlastung'],minHits:3,solution:'Eine richtige Lastverteilung hilft, zulässige Achslasten einzuhalten und sicheres Lenk-, Fahr- und Bremsverhalten zu gewährleisten.'},
{id:'v06-8-04',field:8,topic:'Ladeeinheiten',difficulty:1,type:'mc',question:'Was ist eine Ladeeinheit?',options:['Mehrere Güter, die zu einer transportierbaren Einheit zusammengefasst sind','Nur ein einzelner Lieferschein','Eine Fahrzeugachse','Ein Lagerraum'],correct:[0],solution:'Eine Ladeeinheit fasst Güter so zusammen, dass sie gemeinsam transportiert, gelagert oder umgeschlagen werden können.'},
{id:'v06-8-05',field:8,topic:'Ladungssicherung',difficulty:2,type:'free',question:'Nenne vier Hilfsmittel zur Ladungssicherung.',keywords:['zurrgurt','kantenschutz','antirutschmatte','sperrbalken','netz','keil','zurrkette'],minHits:4,solution:'Zum Beispiel Zurrgurte, Antirutschmatten, Kantenschutz, Sperrbalken, Netze, Keile oder Zurrketten.'},
{id:'v06-8-06',field:8,topic:'Lastverteilung',difficulty:2,type:'mc',question:'Welche Folgen kann eine ungünstige Lastverteilung haben?',options:['Überschrittene Achslasten','Schlechteres Fahrverhalten','Längere Bremswege bzw. instabiles Verhalten','Automatisch geringerer Kraftstoffverbrauch'],correct:[0,1,2],solution:'Falsche Lastverteilung kann Achslasten überschreiten und Fahr-, Lenk- und Bremsverhalten negativ beeinflussen.'},
{id:'v06-8-07',field:8,topic:'Ladungssicherung',difficulty:2,type:'mc',question:'Welche Aussage zu Antirutschmatten ist richtig?',options:['Sie erhöhen den Reibbeiwert','Sie ersetzen immer jede weitere Sicherung','Sie verringern grundsätzlich die Reibung','Sie erhöhen die zulässige Nutzlast'],correct:[0],solution:'Antirutschmatten erhöhen den Reibbeiwert zwischen Ladung und Ladefläche und können so den Sicherungsbedarf reduzieren.'},
{id:'v06-8-08',field:8,topic:'Ladeeinheiten',difficulty:2,type:'free',question:'Welche Vorteile bietet die Bildung stabiler Ladeeinheiten?',keywords:['umschlag','schnell','stabil','transport','lagerung','beschädigung','handling'],minHits:3,solution:'Stabile Ladeeinheiten erleichtern Transport, Lagerung und Umschlag, beschleunigen das Handling und können Schäden reduzieren.'},
{id:'v06-8-09',field:8,topic:'Ladungssicherung',difficulty:3,type:'free',question:'Warum sollte ein Zurrgurt vor der Nutzung kontrolliert werden?',keywords:['beschädigung','riss','schnitt','etikett','ablegereif','sicherheit','tragfähigkeit'],minHits:2,solution:'Beschädigte oder nicht eindeutig gekennzeichnete Zurrmittel können ihre erforderliche Sicherungswirkung verlieren und dürfen gegebenenfalls nicht mehr verwendet werden.'},
{id:'v06-8-10',field:8,topic:'Lastverteilung',difficulty:3,type:'mc',question:'Wo sollten besonders schwere Güter grundsätzlich angeordnet werden?',options:['Möglichst tief und lastverteilungsgerecht','Ganz oben auf leichter Ware','Ausschließlich an der äußersten Fahrzeugkante','Unabhängig von Achslasten'],correct:[0],solution:'Schwere Güter werden möglichst tief und so positioniert, dass Schwerpunkt und zulässige Lastverteilung günstig bleiben.'}
];
