// Erweiterter Fragenpool v0.4: praxisnähere Aufgaben für Lernfelder 1–4.
// Die Schlüsselbegriffe enthalten bewusst Synonyme und alternative Formulierungen.
export const v04Questions = [
  // LF 1 – Güter annehmen und kontrollieren
  {id:'v04-1-01',field:1,topic:'Warenannahme',difficulty:1,type:'free',question:'Ein Lkw trifft zur Warenannahme ein. Nenne vier Kontrollen, die du vor bzw. beim Entladen durchführen kannst.',keywords:['empfänger','lieferadresse','kennzeichen','plombe','lieferschein','frachtbrief','menge','packstücke','anzahl','beschädigung','schaden','verpackung'],minHits:4,solution:'Möglich sind z. B. Empfänger/Lieferadresse, Fahrzeug bzw. Plombe, Begleitpapiere, Anzahl der Packstücke und äußerlich erkennbare Schäden zu kontrollieren.'},
  {id:'v04-1-02',field:1,topic:'Warenannahme',difficulty:2,type:'free',question:'Laut Lieferschein sollen 24 Kartons geliefert werden, auf dem Fahrzeug stehen aber nur 22. Beschreibe dein Vorgehen.',keywords:['zählen','menge','mengendifferenz','abweichung','lieferschein','fahrer','frachtführer','vermerk','dokumentieren','vorbehalt','melden'],minHits:3,solution:'Menge nochmals prüfen, Abweichung mit Lieferschein abgleichen, Fahrer/Frachtführer einbeziehen, die Mengendifferenz auf den Papieren dokumentieren bzw. unter Vorbehalt quittieren und intern melden.'},
  {id:'v04-1-03',field:1,topic:'Mängel',difficulty:2,type:'free',question:'Beim Entladen entdeckst du einen eingedrückten Karton. Der Schaden war bereits von außen erkennbar. Was ist zu tun?',keywords:['offener mangel','sichtbar','dokumentieren','foto','frachtführer','fahrer','vermerk','vorbehalt','quittung','melden'],minHits:3,solution:'Es handelt sich um einen offenen Mangel. Schaden dokumentieren, möglichst fotografieren, Fahrer/Frachtführer hinzuziehen, auf dem Ablieferbeleg konkret vermerken und zuständige Stelle informieren.'},
  {id:'v04-1-04',field:1,topic:'Mängel',difficulty:2,type:'free',question:'Erkläre den Unterschied zwischen offenem und verdecktem Mangel bei einer Lieferung.',keywords:['offen','sichtbar','erkennbar','verdeckt','nicht sichtbar','später','auspacken','prüfung'],minHits:3,solution:'Ein offener Mangel ist bei ordnungsgemäßer Eingangskontrolle erkennbar. Ein verdeckter Mangel zeigt sich erst später, z. B. beim Auspacken oder bei genauer Prüfung.'},
  {id:'v04-1-05',field:1,topic:'Begleitpapiere',difficulty:1,type:'free',question:'Nenne vier Angaben, die du beim Abgleich von Lieferschein und Ware kontrollieren kannst.',keywords:['artikel','artikelnummer','menge','stückzahl','packstücke','bestellnummer','lieferant','absender','empfänger','bezeichnung'],minHits:4,solution:'Typisch sind Artikel/Artikelnummer, Bezeichnung, Menge bzw. Packstückzahl, Bestellnummer, Lieferant/Absender und Empfänger.'},
  {id:'v04-1-06',field:1,topic:'Warenannahme',difficulty:2,type:'free',question:'Warum sollte die Anzahl der Packstücke möglichst vor dem vollständigen Entladen kontrolliert werden?',keywords:['frachtführer','fahrer','abweichung','fehlmenge','nachweis','haftung','reklamation','feststellen'],minHits:2,solution:'So können Fehlmengen bzw. Abweichungen noch in Anwesenheit des Fahrers/Frachtführers festgestellt und dokumentiert werden. Das erleichtert Nachweis und Reklamation.'},
  {id:'v04-1-07',field:1,topic:'Mängel',difficulty:3,type:'free',question:'Eine Palette ist beschädigt, die Ware scheint aber noch verwendbar. Warum solltest du nicht einfach vorbehaltlos unterschreiben?',keywords:['vorbehalt','schaden','haftung','nachweis','reklamation','frachtpapier','dokumentieren','beweis'],minHits:3,solution:'Ein äußerlich erkennbarer Schaden sollte konkret dokumentiert und unter Vorbehalt quittiert werden. Eine vorbehaltlose Quittung kann den späteren Nachweis einer Transportbeschädigung erschweren.'},
  {id:'v04-1-08',field:1,topic:'Warenannahme',difficulty:2,type:'free',question:'Nenne drei Gründe, aus denen eine Warenannahme ganz oder teilweise verweigert werden kann.',keywords:['falschlieferung','falsche ware','starker schaden','beschädigt','keine bestellung','temperatur','gefahr','annahmeverweigerung','unbestellt'],minHits:3,solution:'Je nach betrieblicher Regelung z. B. nicht bestellte/falsche Ware, massive Beschädigung, unzulässige Temperatur oder andere Zustände, die eine sichere bzw. vertragsgemäße Annahme ausschließen.'},
  {id:'v04-1-09',field:1,topic:'Begleitpapiere',difficulty:2,type:'free',question:'Welche Aufgabe hat der Lieferschein bei der Warenannahme?',keywords:['lieferung','inhalt','artikel','menge','kontrolle','abgleich','nachweis','bestellung'],minHits:2,solution:'Der Lieferschein enthält Angaben zur Lieferung und ermöglicht den Abgleich von gelieferter Ware, Artikeln und Mengen mit Bestellung bzw. tatsächlichem Wareneingang.'},
  {id:'v04-1-10',field:1,topic:'Mängel',difficulty:3,type:'free',question:'Nach dem Öffnen einer äußerlich unbeschädigten Verpackung stellst du einen Schaden an der Ware fest. Welche Mangelart liegt nahe und wie gehst du vor?',keywords:['verdeckter mangel','verdeckt','dokumentieren','foto','melden','reklamation','lieferant','frist','unverzüglich'],minHits:3,solution:'Es liegt typischerweise ein verdeckter Mangel vor. Schaden und Verpackung dokumentieren, zuständige Stelle informieren und die Reklamation bzw. Mängelanzeige unverzüglich nach betrieblicher Vorgabe veranlassen.'},

  // LF 2 – Güter lagern
  {id:'v04-2-01',field:2,topic:'Bestände',difficulty:1,type:'free',question:'Erkläre den Mindestbestand und nenne seinen Zweck.',keywords:['sicherheitsbestand','reserve','puffer','lieferverzögerung','mehrverbrauch','engpass','lieferbereitschaft'],minHits:2,solution:'Der Mindest- bzw. Sicherheitsbestand ist eine Reserve. Er soll z. B. Lieferverzögerungen oder unerwarteten Mehrverbrauch überbrücken und Fehlmengen vermeiden.'},
  {id:'v04-2-02',field:2,topic:'Bestände',difficulty:2,type:'free',question:'Der Tagesverbrauch beträgt 40 Stück, die Lieferzeit 5 Tage und der Mindestbestand 100 Stück. Wie hoch ist der Meldebestand? Nenne auch den Rechenweg.',keywords:['300','40','5','100','tagesverbrauch','lieferzeit','mindestbestand'],minHits:3,solution:'Meldebestand = Tagesverbrauch × Lieferzeit + Mindestbestand = 40 × 5 + 100 = 300 Stück.'},
  {id:'v04-2-03',field:2,topic:'Lagerarten',difficulty:2,type:'free',question:'Vergleiche feste und chaotische Lagerplatzordnung. Nenne jeweils einen Vorteil.',keywords:['fest','fester lagerplatz','übersichtlich','einfach','chaotisch','flexibel','auslastung','platznutzung','wms'],minHits:3,solution:'Bei fester Lagerplatzordnung hat jeder Artikel einen definierten Platz, was einfach und übersichtlich sein kann. Chaotische Lagerung vergibt freie Plätze flexibel und ermöglicht meist bessere Flächenauslastung, benötigt aber zuverlässige Lagerverwaltung.'},
  {id:'v04-2-04',field:2,topic:'Lagerarten',difficulty:2,type:'free',question:'Warum eignet sich ein Blocklager nicht für jede Ware?',keywords:['stapelbar','druck','zugriff','fifo','artikel','sortenrein','beschädigung'],minHits:2,solution:'Blocklager setzen geeignete bzw. stapelbare Ladeeinheiten voraus. Der direkte Zugriff auf einzelne Einheiten ist eingeschränkt und FIFO ist ohne passende Organisation schwierig.'},
  {id:'v04-2-05',field:2,topic:'Lagerkennzahlen',difficulty:2,type:'free',question:'Was sagt die Umschlagshäufigkeit aus?',keywords:['wie oft','bestand','erneuert','umgeschlagen','jahresverbrauch','durchschnittlicher lagerbestand'],minHits:2,solution:'Sie zeigt, wie oft sich der durchschnittliche Lagerbestand innerhalb eines Zeitraums, meist eines Jahres, erneuert bzw. verbraucht/abgesetzt wird.'},
  {id:'v04-2-06',field:2,topic:'Lagerkennzahlen',difficulty:3,type:'free',question:'Welche wirtschaftliche Wirkung hat grundsätzlich eine sinkende durchschnittliche Lagerdauer?',keywords:['kapitalbindung','lagerkosten','geringer','liquidität','umschlag','risiko'],minHits:2,solution:'Eine geringere Lagerdauer reduziert tendenziell Kapitalbindung und lagerzeitabhängige Kosten bzw. Risiken. Voraussetzung ist, dass die Lieferbereitschaft nicht darunter leidet.'},
  {id:'v04-2-07',field:2,topic:'Bestände',difficulty:2,type:'free',question:'Was ist der Höchstbestand und warum wird er festgelegt?',keywords:['maximal','bestand','lagerkapazität','kapitalbindung','kosten','platz','überbestand'],minHits:2,solution:'Der Höchstbestand ist die maximal vorgesehene Bestandsmenge. Er begrenzt unter anderem Platzbedarf, Kapitalbindung und Lagerkosten und verhindert unnötige Überbestände.'},
  {id:'v04-2-08',field:2,topic:'Lagerarten',difficulty:2,type:'free',question:'Für welche Güter ist das FIFO-Prinzip besonders sinnvoll? Begründe.',keywords:['älteste','zuerst','verderblich','mhd','alterung','lebensmittel','datum','qualität'],minHits:2,solution:'FIFO ist besonders bei alternden, verderblichen oder datumsabhängigen Gütern sinnvoll: Die zuerst eingelagerte Ware wird zuerst ausgelagert, damit ältere Bestände nicht liegen bleiben.'},
  {id:'v04-2-09',field:2,topic:'Lagerarten',difficulty:2,type:'free',question:'Was bedeutet LIFO und nenne eine typische Lagerform, bei der dieses Prinzip entstehen kann.',keywords:['zuletzt','zuerst','last in first out','einfahrregal','drive in','stapel','block'],minHits:2,solution:'LIFO bedeutet Last In – First Out: Die zuletzt eingelagerte Einheit wird zuerst entnommen. Das kann z. B. bei einseitig bedienten Einfahrregalen oder bestimmten Stapelsituationen auftreten.'},
  {id:'v04-2-10',field:2,topic:'Lagerkennzahlen',difficulty:3,type:'free',question:'Warum ist ein sehr hoher Lagerbestand nicht automatisch positiv, obwohl die Lieferbereitschaft steigt?',keywords:['kapitalbindung','lagerkosten','platz','risiko','verderb','veraltung','beschädigung'],minHits:3,solution:'Hohe Bestände erhöhen Kapitalbindung, Platzbedarf und Lagerkosten sowie Risiken wie Veralterung, Verderb oder Beschädigung. Deshalb muss zwischen Lieferbereitschaft und Wirtschaftlichkeit abgewogen werden.'},

  // LF 3 – Güter bearbeiten
  {id:'v04-3-01',field:3,topic:'Mehrwertleistungen',difficulty:1,type:'free',question:'Erkläre Value Added Services und nenne drei Beispiele aus der Lagerlogistik.',keywords:['zusatzleistung','etikettieren','umpacken','konfektionieren','montage','qualitätskontrolle','verpacken','display'],minHits:3,solution:'Value Added Services sind zusätzliche Leistungen über Lagerung/Transport hinaus, z. B. Etikettieren, Umpacken, Konfektionieren, Qualitätskontrolle, Displaybau oder einfache Montage.'},
  {id:'v04-3-02',field:3,topic:'Kennzeichnung',difficulty:2,type:'free',question:'Warum ist eine eindeutige Artikelkennzeichnung für Lager und Kommissionierung wichtig?',keywords:['identifikation','verwechslung','fehler','bestand','rückverfolgung','kommissionierung','scanner'],minHits:2,solution:'Sie ermöglicht sichere Identifikation und Rückverfolgung, reduziert Verwechslungen und unterstützt korrekte Bestandsführung sowie Kommissionierung.'},
  {id:'v04-3-03',field:3,topic:'Kennzeichnung',difficulty:2,type:'free',question:'Nenne drei Vorteile eines Barcodes gegenüber einer rein manuellen Erfassung.',keywords:['schnell','fehler','automatisch','scanner','daten','erfassung','eindeutig','zeit'],minHits:3,solution:'Barcode-Scanning ermöglicht schnelle, weitgehend automatisierte und eindeutige Datenerfassung und reduziert Übertragungs- bzw. Eingabefehler.'},
  {id:'v04-3-04',field:3,topic:'Kennzeichnung',difficulty:2,type:'free',question:'Welche Informationen können für die Rückverfolgbarkeit einer Ware wichtig sein?',keywords:['charge','chargennummer','serie','seriennummer','mhd','datum','artikelnummer','lieferant','los'],minHits:3,solution:'Je nach Ware z. B. Artikelnummer, Charge/Los, Seriennummer, MHD/Datum und Lieferanten- oder Produktionsinformationen.'},
  {id:'v04-3-05',field:3,topic:'Verpackung',difficulty:2,type:'free',question:'Eine Ware wird vor dem Versand umgepackt. Nenne drei Punkte, die du dabei beachten solltest.',keywords:['schutz','geeignet','kennzeichnung','etikett','menge','vollständigkeit','beschädigung','sauber','gefahrgut'],minHits:3,solution:'Geeigneten Schutz und Packmittel wählen, Ware/Menge auf Zustand und Vollständigkeit prüfen und erforderliche Kennzeichnungen/Etiketten korrekt übernehmen bzw. neu anbringen.'},
  {id:'v04-3-06',field:3,topic:'Mehrwertleistungen',difficulty:2,type:'free',question:'Ein Kunde verlangt, dass 12 Einzelartikel zu einem Verkaufsset zusammengestellt werden. Wie nennt man diese Zusatzleistung und was muss besonders kontrolliert werden?',keywords:['konfektionieren','konfektionierung','set','menge','vollständigkeit','artikel','qualität'],minHits:2,solution:'Das Zusammenstellen zu Verkaufseinheiten ist eine Form der Konfektionierung. Wichtig sind insbesondere richtige Artikel, Stückzahl/Vollständigkeit und Qualität.'},
  {id:'v04-3-07',field:3,topic:'Kennzeichnung',difficulty:3,type:'free',question:'Warum darf bei einer Umpackaktion eine notwendige Kennzeichnung nicht einfach verloren gehen?',keywords:['identifikation','rückverfolgung','gefahr','sicherheit','charge','information','gesetz','verwechslung'],minHits:2,solution:'Notwendige Kennzeichnungen sichern Identifikation, Rückverfolgbarkeit und ggf. Sicherheits-/Gefahreninformationen. Beim Umpacken müssen erforderliche Angaben deshalb erhalten bzw. korrekt übertragen werden.'},
  {id:'v04-3-08',field:3,topic:'Verpackung',difficulty:2,type:'free',question:'Was ist beim Bearbeiten beschädigter Ware vor einer Neuverpackung sinnvoll?',keywords:['prüfen','schaden','dokumentieren','aussortieren','qualität','freigabe','melden'],minHits:2,solution:'Schaden und Warenzustand prüfen und dokumentieren, nicht verwendbare Ware aussortieren bzw. sperren und nach betrieblicher Vorgabe Freigabe/Meldung veranlassen, bevor neu verpackt wird.'},
  {id:'v04-3-09',field:3,topic:'Mehrwertleistungen',difficulty:2,type:'free',question:'Warum können Value Added Services für einen Logistikdienstleister wirtschaftlich interessant sein?',keywords:['mehrwert','kunde','zusatzleistung','erlös','bindung','service','wettbewerb'],minHits:2,solution:'Zusatzleistungen schaffen Kundennutzen, können zusätzliche Erlöse erzeugen, die Kundenbindung erhöhen und den Dienstleister vom Wettbewerb differenzieren.'},
  {id:'v04-3-10',field:3,topic:'Kennzeichnung',difficulty:2,type:'free',question:'Ein Scanner liest einen Barcode nicht. Nenne drei sinnvolle Maßnahmen, bevor du die Ware weiterbearbeitest.',keywords:['reinigen','prüfen','beschädigt','manuell','artikelnummer','neu etikettieren','etikett','system','melden'],minHits:3,solution:'Etikett auf Verschmutzung/Beschädigung prüfen und ggf. reinigen, Artikel anhand weiterer Daten sicher identifizieren, nach Vorgabe manuell erfassen bzw. korrekt neu etikettieren und Fehler ggf. melden.'},

  // LF 4 – Güter im Betrieb transportieren
  {id:'v04-4-01',field:4,topic:'Fördermittel',difficulty:1,type:'free',question:'Erkläre den Unterschied zwischen Stetig- und Unstetigförderern und nenne je ein Beispiel.',keywords:['kontinuierlich','stetig','förderband','rollenbahn','einzeln','unstetig','stapler','hubwagen'],minHits:3,solution:'Stetigförderer bewegen Güter kontinuierlich, z. B. Förderband/Rollenbahn. Unstetigförderer führen einzelne Transportspiele aus, z. B. Gabelstapler oder Hubwagen.'},
  {id:'v04-4-02',field:4,topic:'Sicherheit',difficulty:2,type:'free',question:'Nenne vier Regeln für das sichere Fahren mit einem Gabelstapler im Betrieb.',keywords:['geschwindigkeit','sicht','fahrweg','personen','last','gabel','abstand','kurve','rückwärts'],minHits:4,solution:'Z. B. Geschwindigkeit anpassen, vorgeschriebene Fahrwege nutzen, Personen schützen/Abstand halten, Last sicher und bodennah transportieren sowie bei verdeckter Sicht nach betrieblicher Regelung rückwärts fahren.'},
  {id:'v04-4-03',field:4,topic:'Sicherheit',difficulty:2,type:'free',question:'Warum soll eine Last beim Staplertransport möglichst bodennah geführt werden?',keywords:['schwerpunkt','stabil','kippen','kippsicherheit','sicht','sicherheit'],minHits:2,solution:'Eine niedrige Lastlage hält den Gesamtschwerpunkt günstiger und verbessert die Kippsicherheit. Hoch angehobene Lasten verschlechtern die Stabilität.'},
  {id:'v04-4-04',field:4,topic:'Sicherheit',difficulty:3,type:'free',question:'Die Last auf dem Stapler versperrt dir die Sicht nach vorn. Wie solltest du reagieren?',keywords:['rückwärts','sicht','einweiser','langsam','fahrtrichtung','sicher'],minHits:2,solution:'Nicht blind vorwärtsfahren. Nach betrieblicher Regelung mit freier Sicht, häufig rückwärts, langsam und aufmerksam fahren bzw. bei Bedarf einen Einweiser einsetzen.'},
  {id:'v04-4-05',field:4,topic:'Fördermittel',difficulty:2,type:'free',question:'Nach welchen Kriterien wählst du ein geeignetes innerbetriebliches Fördermittel aus? Nenne vier.',keywords:['gewicht','abmessung','größe','strecke','weg','häufigkeit','menge','boden','höhe','kosten','ware'],minHits:4,solution:'Unter anderem Art, Gewicht und Abmessungen der Ware, Transportstrecke/-häufigkeit, Boden und Wege, benötigte Hubhöhe, Durchsatz und Wirtschaftlichkeit.'},
  {id:'v04-4-06',field:4,topic:'Transportwege',difficulty:2,type:'free',question:'Warum sollten Fuß- und Fahrwege im Lager möglichst eindeutig gekennzeichnet und getrennt sein?',keywords:['unfall','sicherheit','personen','kollision','verkehr','übersicht','stapler'],minHits:2,solution:'Klare Trennung und Kennzeichnung reduziert Begegnungs- und Kollisionsrisiken zwischen Personen und Flurförderzeugen und macht Verkehrsabläufe übersichtlicher.'},
  {id:'v04-4-07',field:4,topic:'Sicherheit',difficulty:3,type:'free',question:'Du bemerkst vor Fahrtbeginn einen Schaden am Gabelstapler, der die Sicherheit beeinträchtigen könnte. Was tust du?',keywords:['nicht fahren','stilllegen','melden','vorgesetzter','schaden','kennzeichnen','reparatur','sichern'],minHits:2,solution:'Stapler nicht weiter benutzen bzw. sichern, Schaden nach betrieblicher Vorgabe melden und das Fahrzeug erst nach fachgerechter Prüfung/Freigabe wieder einsetzen.'},
  {id:'v04-4-08',field:4,topic:'Transportwege',difficulty:2,type:'free',question:'Nenne drei Gefahren, die bei innerbetrieblichen Transportwegen berücksichtigt werden müssen.',keywords:['engstelle','kreuzung','tür','rampe','gefälle','person','sicht','boden','hindernis','kollision'],minHits:3,solution:'Z. B. unübersichtliche Kreuzungen/Engstellen, Türen und Tore, Rampen/Gefälle, Personenverkehr, schlechte Sicht, beschädigte Böden oder Hindernisse.'},
  {id:'v04-4-09',field:4,topic:'Fördermittel',difficulty:2,type:'free',question:'Wann ist ein Handhubwagen gegenüber einem Gabelstapler sinnvoll?',keywords:['kurze strecke','ebener boden','palette','gering','kosten','wendig','kein hub','klein'],minHits:2,solution:'Für kurze, ebene Transportwege von Paletten ohne große Hubhöhe kann ein Handhubwagen einfach, wendig und wirtschaftlich sein.'},
  {id:'v04-4-10',field:4,topic:'Sicherheit',difficulty:3,type:'free',question:'Warum muss die Tragfähigkeit eines Flurförderzeugs zur Last und zur Hubhöhe passen?',keywords:['tragfähigkeit','lastschwerpunkt','hubhöhe','kippen','stabilität','überlastung','lastdiagramm'],minHits:3,solution:'Die zulässige Tragfähigkeit hängt u. a. von Lastschwerpunkt und Hubhöhe ab. Überschreitung kann Stabilität und Kippsicherheit gefährden; deshalb sind Tragfähigkeits-/Lastdiagramm und Herstellerangaben zu beachten.'}
];
