'use client';
import {useEffect,useRef,useState} from 'react';
import {safetySigns,signKinds,signImage,shuffledSigns,signOptions} from './safety-sign-data';
import {shapeQuestions,shapeGrade,signQuestion,pictureKey,shapeKey,uncertainSignPool,signRound,recordSignReview,readSignReviews,signReviewStorageKey} from './sign-training';
import {scoreAnswerHybrid} from './hybrid-score';
import {scoreAnswer} from './data';
import './safety-signs.css';
const sources=Object.fromEntries([['mandatory','gebotszeichen'],['prohibited','verbotszeichen'],['warning','warnzeichen'],['rescue','rettungszeichen'],['fire','brandschutzzeichen'],['ghs','kennzeichnung-von-gefahrstoffen']].map(([kind,path])=>[kind,`https://www.bghm.de/arbeitsschuetzer/praxishilfen/sicherheitszeichen/${path}`]));
function SignPicture({sign,onFailure}){const [failed,setFailed]=useState(false);return <div className={`signPicture ${sign.kind}`}>{failed?<span className="signFallback" role="img" aria-label={`Bild für ${sign.code} nicht geladen`}>{signKinds.find(k=>k.id===sign.kind)?.mark}<small>Bild nicht geladen</small></span>:<img src={signImage(sign.code)} alt={`Sicherheitszeichen ${sign.code}`} onError={()=>{setFailed(true);onFailure?.()}} loading="lazy"/>}</div>}
export default function SafetySigns({onClose}){
 const [kind,setKind]=useState('all'),[mode,setMode]=useState('catalog'),[search,setSearch]=useState(''),[reviews,setReviews]=useState({}),[storageError,setStorageError]=useState(false);
 const [questions,setQuestions]=useState([]),[index,setIndex]=useState(0),[options,setOptions]=useState([]),[answer,setAnswer]=useState(''),[result,setResult]=useState(null),[results,setResults]=useState([]),[busy,setBusy]=useState(false),[imageFailed,setImageFailed]=useState(false),[shape,setShape]=useState(''),[color,setColor]=useState(''),[lastMode,setLastMode]=useState('quiz'),[onlyWeak,setOnlyWeak]=useState(false);
 const userId=useRef('guest'),generation=useRef(0),lock=useRef(false),recorded=useRef(false),reviewsRef=useRef({});
 useEffect(()=>{try{userId.current=localStorage.getItem('lagerlogik-active-user')||'guest';const stored=readSignReviews(localStorage,userId.current);reviewsRef.current=stored;setReviews(stored)}catch{}return()=>{generation.current++;lock.current=false}},[]);
 const pool=safetySigns.filter(s=>kind==='all'||s.kind===kind),weak=uncertainSignPool(pool,reviews),visible=pool.filter(s=>`${s.code} ${s.label}`.toLocaleLowerCase('de').includes(search.toLocaleLowerCase('de').trim())),current=questions[index];
 function remember(key,score){const next=recordSignReview(reviewsRef.current,key,score);reviewsRef.current=next;setReviews(next);try{localStorage.setItem(signReviewStorageKey(userId.current),JSON.stringify(next));setStorageError(false)}catch{setStorageError(true)}}
 function clear(){generation.current++;lock.current=false;recorded.current=false;setBusy(false);setAnswer('');setResult(null);setImageFailed(false);setShape('');setColor('')}
 function catalog(nextKind=kind){clear();setKind(nextKind);setMode('catalog')}
 function start(nextMode='quiz',repeat=false){clear();const picked=nextMode==='shape'?[...shuffledSigns(shapeQuestions.filter(q=>reviewsRef.current[shapeKey(q.id)]?.score<80)),...shuffledSigns(shapeQuestions.filter(q=>!(reviewsRef.current[shapeKey(q.id)]?.score<80)))]:signRound(pool,reviewsRef.current,repeat);if(!picked.length)return;setQuestions(picked);setIndex(0);setResults([]);setOptions(nextMode==='quiz'?signOptions(picked[0],pool):[]);setLastMode(nextMode);setOnlyWeak(repeat);setMode(nextMode)}
 function save(score,reason='',extra={}){if(recorded.current)return;recorded.current=true;const entry={score,reason,...extra};setResult(entry);setResults(old=>[...old,{item:current,answer, ...entry}]);remember(mode==='shape'?shapeKey(current.id):pictureKey(current.code),score)}
 async function checkFree(){if(lock.current||result||imageFailed||!answer.trim())return;lock.current=true;const ticket=++generation.current;setBusy(true);try{const graded=await scoreAnswerHybrid(answer,signQuestion(current),scoreAnswer);if(ticket!==generation.current)return;if(graded.aiStatus?.includes('fehlgeschlagen'))setResult({unavailable:true});else save(graded.score,graded.aiReason||'Mit der Bedeutung des Zeichens abgeglichen.')}finally{if(ticket===generation.current){lock.current=false;setBusy(false)}}}
 function next(){clear();if(index+1>=questions.length){setMode('result');return}const q=questions[index+1];setIndex(i=>i+1);if(mode==='quiz')setOptions(signOptions(q,pool))}
 const average=results.length?Math.round(results.reduce((n,r)=>n+r.score,0)/results.length):0;
 return <section className="signsShell"><header className="signsHead"><div><span className="kicker">ARBEITSSCHUTZ</span><h1>Sicherheitszeichen & Gefahrstoffe</h1><p>Bild ansehen und Bedeutung selbst nennen, Antworten auswählen oder Form und Hintergrundfarbe üben.</p></div><button className="secondary" onClick={onClose}>← Praxiswelt</button></header>
 {mode==='catalog'&&<div className="signsRule">{signKinds.map(k=><div key={k.id}><span className={`signRuleMark ${k.id}`}>{k.mark}</span><strong>{k.name}</strong><small>{k.rule}</small></div>)}</div>}
 <div className="signsControls"><div className="signsTabs" role="group" aria-label="Zeichenart">{[['all','Alle'],...signKinds.map(k=>[k.id,k.label])].map(([id,label])=><button key={id} className={kind===id?'active':''} onClick={()=>catalog(id)}>{label}</button>)}</div><div className="signsTabs" role="group" aria-label="Lernart"><button className={mode==='catalog'?'active':''} onClick={()=>catalog()}>Übersicht</button><button className={mode==='quiz'?'active':''} onClick={()=>start('quiz')}>10 Zeichen abfragen</button><button className={mode==='free'?'active':''} onClick={()=>start('free')}>Bedeutung selbst eingeben</button><button className={mode==='shape'?'active':''} onClick={()=>start('shape')}>Form & Farbe</button></div><div className="signsRepeat"><span>{weak.length} unsichere Zeichen in dieser Auswahl</span><button disabled={!weak.length} onClick={()=>start('free',true)}>Unsichere Zeichen wiederholen</button><small>Auf diesem Gerät für dein Konto gespeichert.{storageError?' Speichern momentan nicht möglich; Fortschritt bleibt nur bis zum Verlassen erhalten.':''}</small></div></div>
 {mode==='catalog'&&<><label className="signsSearch">Zeichen suchen <input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Code oder Bedeutung eingeben"/></label><p className="signsCount">{visible.length} Zeichen · Karte antippen und Bedeutung aufdecken</p><div className="signsGrid">{visible.map(sign=><SignCard key={sign.code} sign={sign} unsure={reviews[pictureKey(sign.code)]?.score<80} onRate={score=>remember(pictureKey(sign.code),score)}/>)}</div>{!visible.length&&<p>Kein passendes Zeichen gefunden.</p>}</>}
 {['quiz','free','shape'].includes(mode)&&current&&<div className="signQuiz card"><div className="signQuizTop"><span>Frage {index+1} von {questions.length}</span><strong>{results.filter(r=>r.score===100).length} richtig</strong></div>{mode==='shape'?<><h2>{current.name}: Welche Form und Hintergrundfarbe?</h2><p className="signShapeHint">Diese Runde behandelt alle fünf Sicherheitszeichenarten. Gefragt ist die Grundfläche. Rand, Schrägbalken und Bildzeichen sind davon zu unterscheiden.</p><div className="signShapeInputs"><label>Form<select value={shape} disabled={!!result} onChange={e=>setShape(e.target.value)}><option value="">Auswählen …</option>{['Kreis','Dreieck','Quadrat oder Rechteck','Raute'].map(v=><option key={v}>{v}</option>)}</select></label><label>Hintergrundfarbe<select value={color} disabled={!!result} onChange={e=>setColor(e.target.value)}><option value="">Auswählen …</option>{['Weiß','Blau','Gelb','Grün','Rot','Schwarz'].map(v=><option key={v}>{v}</option>)}</select></label></div>{!result&&<button className="primary" disabled={!shape||!color} onClick={()=>{const grade=shapeGrade(current,shape,color);save(grade.score,current.explanation,grade)}}>Antwort prüfen</button>}</>:<><SignPicture key={current.code} sign={current} onFailure={()=>setImageFailed(true)}/><h2>Was bedeutet dieses Zeichen?</h2>{imageFailed?<div role="status"><p>Das Bild konnte nicht geladen werden. Diese Frage wird nicht bewertet.</p><button className="secondary" onClick={next}>{index+1===questions.length?'Runde beenden':'Zeichen überspringen'}</button></div>:mode==='quiz'?<div className="signQuizOptions">{options.map(option=><button key={option.code} disabled={!!result} className={result?(option.code===current.code?'right':result.selected===option.code?'wrong':''):''} onClick={()=>{if(result||lock.current)return;lock.current=true;save(option.code===current.code?100:0,'',{selected:option.code})}}>{option.label}</button>)}</div>:<><label className="signFreeAnswer">Deine Antwort<textarea value={answer} disabled={!!result||busy} onChange={e=>setAnswer(e.target.value)} placeholder="Bedeutung in eigenen Worten eingeben"/></label>{!result&&<div className="signResultActions"><button className="primary" disabled={!answer.trim()||busy} onClick={checkFree}>{busy?'Antwort wird geprüft …':'Antwort prüfen'}</button><button className="secondary" disabled={busy} onClick={()=>save(0,'Für die Wiederholung vorgemerkt.')}>Weiß ich nicht</button></div>}</>}</>}
 {result&&<div className="signQuizFeedback" role="status">{result.unavailable?<><p>Die Antwortprüfung ist gerade nicht erreichbar. Vergleiche deine Antwort mit der Bedeutung:</p><b>{current.label}</b><div className="signResultActions"><button onClick={()=>save(0,'Selbst eingeschätzt')}>Noch unsicher</button><button onClick={()=>save(100,'Selbst eingeschätzt')}>Gewusst</button></div></>:<><b>{result.score===100?'Richtig!':result.score>0?'Teilweise richtig.':'Noch nicht ganz.'} {result.score}%</b>{mode==='shape'?<p>Form: {current.shape} · Hintergrund: {current.background}<br/>{current.explanation}</p>:<p>{current.code} · {current.label}</p>}{result.reason&&<p>{result.reason}</p>}<button className="primary" onClick={next}>{index+1===questions.length?'Ergebnis ansehen':mode==='shape'?'Nächste Zeichenart':'Nächstes Zeichen'}</button></>}</div>}</div>}
 {mode==='result'&&<div className="signQuiz card"><h2>{results.filter(r=>r.score===100).length} von {results.length} richtig</h2><p>{average}% · {results.length} bewertet{questions.length!==results.length?` · ${questions.length-results.length} ohne Bild übersprungen`:''}</p>{results.length===0?<p>Es konnte kein Zeichen bewertet werden. Prüfe deine Internetverbindung.</p>:<p>{average===100?'Alle Antworten richtig!':'Unsichere Zeichen werden für die nächste Runde vorgemerkt.'}</p>}<div className="signRoundReview">{results.filter(r=>r.score<100).map(r=><p key={r.item.code||r.item.id}><b>{r.score}% · {r.item.code||r.item.name}</b><br/>{r.item.label||r.item.explanation}</p>)}</div><div className="signResultActions"><button className="primary" onClick={()=>start(lastMode,onlyWeak&&weak.length>0)}>Neue Runde</button><button className="secondary" onClick={()=>catalog()}>Alle Zeichen ansehen</button>{weak.length>0&&<button className="secondary" onClick={()=>start('free',true)}>Unsichere Zeichen wiederholen</button>}</div></div>}
 <p className="signsSources">Auswahl für das Lagertraining; kein vollständiger Normenkatalog. GHS-Piktogramme können mehrere Gefahren beschreiben: Etikett, Sicherheitsdatenblatt und Betriebsanweisung beachten. Quellen: {signKinds.map((k,i)=><span key={k.id}>{i>0?' · ':''}<a href={sources[k.id]} target="_blank" rel="noreferrer">{k.label} (BGHM)</a></span>)}. Piktogramme: Wikimedia Commons; Internetverbindung erforderlich.</p></section>;
}
function SignCard({sign,unsure,onRate}){const [open,setOpen]=useState(false);return <div className="signCardWrap"><button className={`signCard ${open?'revealed':''}`} onClick={()=>setOpen(v=>!v)} aria-expanded={open}><SignPicture sign={sign}/><span className="signCode">{open?sign.code:'Was bedeutet das?'}</span><strong>{open?sign.label:'Aufdecken'}</strong>{unsure&&<small className="signUnsure">Noch unsicher</small>}</button>{open&&<div className="signCardRating"><button onClick={()=>onRate(0)}>Noch unsicher</button><button onClick={()=>onRate(100)}>Gewusst</button></div>}</div>}
