'use client';
import {useMemo,useState} from 'react';
const EVENTS=[
 {time:'06:10',title:'Der erste LKW ist da',text:'Der Fahrer drängt. Beim Öffnen siehst du eine eingedrückte Ecke an einer Palette.',choices:[['Schaden dokumentieren, Fahrer einbeziehen und Ware getrennt halten',{quality:12,time:-4,cost:-20}],['Gesamte Lieferung zunächst auf Klärfläche stellen und Kontrolle priorisieren',{quality:9,time:-7,cost:-50}],['Nur die Ecke fotografieren und normal einlagern',{quality:-14,time:6,cost:-180}]]},
 {time:'07:05',title:'Kommissionierung hängt',text:'Ein Schnelldreher liegt ganz hinten im Lager. Drei Aufträge warten bereits, einer davon ist Express.',choices:[['Express priorisieren und übrige Laufwege bündeln',{quality:8,time:9,cost:-20}],['Alle drei strikt nach Auftragseingang bearbeiten',{quality:5,time:-5,cost:0}],['Bestand ohne Buchung näher ans Tor stellen',{quality:-16,time:7,cost:-160}]]},
 {time:'08:20',title:'Bestandsdifferenz',text:'Im System stehen 24 Stück, am Lagerplatz liegen nur 19. Zwei Aufträge benötigen zusammen 18 Stück.',choices:[['Nachzählen und Buchungen prüfen, verfügbare 18 Stück danach freigeben',{quality:11,time:-4,cost:-20}],['Bestand sofort auf 19 korrigieren und kommissionieren',{quality:-7,time:5,cost:-70}],['24 Stück bestätigen, damit das System keinen Fehler meldet',{quality:-24,time:8,cost:-240}]]},
 {time:'09:40',title:'Versand unter Druck',text:'Ein Expressauftrag muss heute raus. Das Label zeigt Hausnummer 18, im Auftrag steht 81. Der Kunde ist telefonisch nicht erreichbar.',choices:[['Verlässliche Auftragsdaten prüfen, Label korrigieren und dokumentieren',{quality:12,time:-3,cost:-10}],['Sendung bis zur Kundenrückmeldung komplett stoppen',{quality:5,time:-9,cost:-80}],['Mit Hausnummer 18 versenden, weil das Label bereits gedruckt ist',{quality:-24,time:8,cost:-320}]]},
 {time:'11:15',title:'Verkehrsweg verengt',text:'Eine Palette ragt etwa 30 cm in einen markierten Verkehrsweg. Der Bereich ist gerade stark frequentiert.',choices:[['Palette sofort auf einen zulässigen Stellplatz umsetzen',{quality:12,time:-5,cost:-10}],['Bereich kurz absichern und Palette beim nächsten freien Stapler umsetzen',{quality:7,time:-2,cost:-20}],['Warnschild aufstellen und Palette bis Schichtende stehen lassen',{quality:-13,time:5,cost:-100}]]},
 {time:'12:30',title:'Lieferverzug droht',text:'Ein wichtiger Artikel kommt zwei Tage später. Der Bestand reicht rechnerisch nur noch für einen Tag.',choices:[['Bedarf und offene Aufträge prüfen, dann Termin oder Alternative abstimmen',{quality:11,time:-3,cost:-40}],['Sicherheitsmenge kurzfristig bei einem freigegebenen Zweitlieferanten beschaffen',{quality:7,time:2,cost:-210}],['Erst reagieren, wenn der Bestand tatsächlich null ist',{quality:-17,time:5,cost:-190}]]},
 {time:'13:45',title:'Schwere Metallteile',text:'Die Teile sollen per Paketdienst raus. Der vorhandene Karton ist stabil, enthält aber viel Freiraum.',choices:[['Freiraum mit geeigneter Polsterung füllen und Bewegung verhindern',{quality:11,time:-4,cost:-35}],['Kleineren geeigneten Karton verwenden und neu packen',{quality:10,time:-6,cost:-45}],['Karton nur außen mehrfach mit Klebeband umwickeln',{quality:-13,time:5,cost:-130}]]},
 {time:'14:50',title:'Schichtübergabe',text:'Zwei Abweichungen sind noch nicht abschließend geklärt. Die Folgeschicht ist vollständig besetzt.',choices:[['Status, bisherige Prüfung und nächste Schritte nachvollziehbar übergeben',{quality:11,time:-3,cost:0}],['Beide Fälle selbst fertig bearbeiten und Übergabe warten lassen',{quality:6,time:-8,cost:-40}],['Nur die Vorgangsnummern auf einen Zettel schreiben',{quality:-10,time:4,cost:-70}]]},
];
function shuffle(a){const n=[...a];for(let i=n.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[n[i],n[j]]=[n[j],n[i]]}return n}
export default function ShiftSimulator({onClose}){const [i,setI]=useState(0),[score,setScore]=useState({quality:60,time:50,cost:1500}),[log,setLog]=useState([]),[done,setDone]=useState(false),[run,setRun]=useState(1);const e=EVENTS[i],choices=useMemo(()=>shuffle(e.choices),[i,run]);function choose(c){const d=c[1],n={quality:Math.max(0,Math.min(100,score.quality+d.quality)),time:Math.max(0,Math.min(100,score.time+d.time)),cost:Math.max(0,score.cost+d.cost)};setScore(n);setLog(x=>[...x,{title:e.title,choice:c[0],impact:d.quality+d.time}]);if(i===EVENTS.length-1)setDone(true);else setI(i+1)}function restart(){setI(0);setScore({quality:60,time:50,cost:1500});setLog([]);setDone(false);setRun(x=>x+1)}const total=Math.round(score.quality*.55+score.time*.35+Math.min(100,score.cost/15)*.10);return <section className="shiftWrap"><div className="shiftTop"><button onClick={onClose}>← Aktivitäten</button><div><b>🏭 SCHICHT-SIMULATOR</b><small> Frühschicht · 06:00–15:00</small></div></div><div className="shiftHud"><div><span>Qualität</span><strong>{score.quality}%</strong></div><div><span>Tempo</span><strong>{score.time}%</strong></div><div><span>Kostenreserve</span><strong>{score.cost.toLocaleString('de-DE')} €</strong></div><div><span>Ereignis</span><strong>{Math.min(i+1,EVENTS.length)}/{EVENTS.length}</strong></div></div>{!done?<div className="shiftScene"><div className="warehouse"><div className="rack">▦ ▦ ▦<br/>▦ ▦ ▦</div><div className="fork">▰▰<span>▥</span></div><div className="dock">TOR 3</div></div><article className="shiftCard"><span className="shiftTime">{e.time} UHR</span><h1>{e.title}</h1><p>{e.text}</p><h3>Wie entscheidest du?</h3><div className="shiftChoices">{choices.map((c,x)=><button key={c[0]} onClick={()=>choose(c)}><b>{String.fromCharCode(65+x)}</b>{c[0]}</button>)}</div></article></div>:<div className="shiftResult"><span>FEIERABEND</span><h1>{total}% Schichtleistung</h1><p>{total>=85?'Sehr starke Schicht. Sicherheit, Qualität und Durchsatz blieben im Gleichgewicht. 🏆':total>=65?'Solide Schicht. Einige Entscheidungen hatten echte Zielkonflikte.':'Heute haben sich mehrere Entscheidungen gegenseitig auf die Füße gestellt. 😅'}</p><div className="shiftLog">{log.map((l,x)=><div key={x}><span>{l.impact>=8?'✓':l.impact>=0?'≈':'!'} </span><b>{l.title}</b><small>{l.choice}</small></div>)}</div><button className="shiftRestart" onClick={restart}>↻ Neue Schicht</button></div>}</section>}
