'use client';
import {useState} from 'react';
const EVENTS=[
 {time:'06:10',title:'Der erste LKW ist da',text:'Der Fahrer drängt. Beim Öffnen siehst du eine eingedrückte Ecke an einer Palette.',choices:[['Schaden dokumentieren, Fahrer einbeziehen und Ware sperren',{quality:12,time:-2,cost:0}],['Erst entladen und später schauen',{quality:-12,time:5,cost:-120}],['Palette direkt einlagern',{quality:-22,time:8,cost:-300}]]},
 {time:'07:05',title:'Kommissionierung hängt',text:'Ein Schnelldreher liegt ganz hinten im Lager. Drei Aufträge warten bereits.',choices:[['Aufträge priorisieren und Laufweg bündeln',{quality:8,time:8,cost:80}],['Jeden Auftrag einzeln laufen',{quality:0,time:-8,cost:0}],['Den Artikel ohne Buchung näher ans Tor stellen',{quality:-18,time:6,cost:-180}]]},
 {time:'08:20',title:'Bestandsdifferenz',text:'Im System stehen 24 Stück, am Lagerplatz liegen nur 19.',choices:[['Nachzählen, Buchungen prüfen und Differenz klären',{quality:10,time:-3,cost:40}],['Systembestand einfach auf 19 ändern',{quality:-15,time:5,cost:-120}],['Die fünf fehlenden Stück trotzdem bestätigen',{quality:-25,time:7,cost:-250}]]},
 {time:'09:40',title:'Versand unter Druck',text:'Ein Expressauftrag muss heute raus. Das Versandlabel zeigt aber eine andere Hausnummer als der Auftrag.',choices:[['Auftragsdaten prüfen und Label korrigieren',{quality:12,time:-3,cost:60}],['Versenden, wird schon stimmen',{quality:-25,time:7,cost:-350}],['Paket bis morgen liegen lassen',{quality:-8,time:-8,cost:-100}]]},
 {time:'11:15',title:'Sicherheitsproblem',text:'Eine Palette blockiert teilweise einen markierten Verkehrsweg.',choices:[['Verkehrsweg sofort freimachen',{quality:12,time:-4,cost:20}],['Warnschild daneben stellen',{quality:-10,time:4,cost:-80}],['Bis Schichtende ignorieren',{quality:-25,time:7,cost:-220}]]},
 {time:'12:30',title:'Lieferant ruft an',text:'Ein wichtiger Artikel kommt zwei Tage später. Der Bestand reicht wahrscheinlich nur noch für einen Tag.',choices:[['Bestand und Bedarf prüfen, Alternative/Termin abstimmen',{quality:10,time:-3,cost:-40}],['Sofort doppelte Menge bei irgendeinem Anbieter kaufen',{quality:-5,time:2,cost:-260}],['Nichts tun und hoffen',{quality:-18,time:5,cost:-200}]]},
 {time:'13:45',title:'Verpackungsfrage',text:'Schwere Metallteile sollen per Paketdienst raus. Im Karton ist noch viel Freiraum.',choices:[['Geeignetes Packmittel nutzen und gegen Bewegung sichern',{quality:12,time:-3,cost:-20}],['Nur mehr Klebeband außen herum',{quality:-12,time:4,cost:-160}],['So versenden',{quality:-22,time:7,cost:-300}]]},
 {time:'14:50',title:'Schichtübergabe',text:'Zwei ungeklärte Abweichungen sind noch offen. Die nächste Schicht beginnt gleich.',choices:[['Abweichungen sauber dokumentieren und übergeben',{quality:10,time:-2,cost:30}],['Zettel auf den Tisch legen',{quality:-8,time:4,cost:-80}],['Nichts sagen',{quality:-18,time:7,cost:-180}]]},
];
export default function ShiftSimulator({onClose}){const [i,setI]=useState(0),[score,setScore]=useState({quality:60,time:50,cost:1500}),[log,setLog]=useState([]),[done,setDone]=useState(false);const e=EVENTS[i];function choose(c){const d=c[1],n={quality:Math.max(0,Math.min(100,score.quality+d.quality)),time:Math.max(0,Math.min(100,score.time+d.time)),cost:score.cost+d.cost};setScore(n);setLog(x=>[...x,{title:e.title,choice:c[0],good:d.quality>0}]);if(i===EVENTS.length-1)setDone(true);else setI(i+1)}function restart(){setI(0);setScore({quality:60,time:50,cost:1500});setLog([]);setDone(false)}const total=Math.round((score.quality+score.time)/2);return <section className="shiftWrap"><div className="shiftTop"><button onClick={onClose}>← Übersicht</button><div><b>🏭 SCHICHT-SIMULATOR</b><small> Frühschicht · 06:00–15:00</small></div></div><div className="shiftHud"><div><span>Qualität</span><strong>{score.quality}%</strong></div><div><span>Tempo</span><strong>{score.time}%</strong></div><div><span>Budget</span><strong>{score.cost.toLocaleString('de-DE')} €</strong></div><div><span>Ereignis</span><strong>{Math.min(i+1,EVENTS.length)}/{EVENTS.length}</strong></div></div>{!done?<div className="shiftScene"><div className="warehouse"><div className="rack">▦ ▦ ▦<br/>▦ ▦ ▦</div><div className="fork">▰▰<span>▥</span></div><div className="dock">TOR 3</div></div><article className="shiftCard"><span className="shiftTime">{e.time} UHR</span><h1>{e.title}</h1><p>{e.text}</p><h3>Was machst du?</h3><div className="shiftChoices">{e.choices.map((c,x)=><button key={x} onClick={()=>choose(c)}><b>{String.fromCharCode(65+x)}</b>{c[0]}</button>)}</div></article></div>:<div className="shiftResult"><span>FEIERABEND</span><h1>{total}% Schichtleistung</h1><p>{total>=85?'Schichtmeister. Das Lager läuft sauber und kontrolliert. 🏆':total>=65?'Solide Schicht. Ein paar Prozesse rumpeln noch.':'Heute standen einige Paletten quer im Prozess. Morgen besser. 😅'}</p><div className="shiftLog">{log.map((l,x)=><div key={x}><span>{l.good?'✓':'!'} </span><b>{l.title}</b><small>{l.choice}</small></div>)}</div><button className="shiftRestart" onClick={restart}>↻ Neue Schicht</button></div>}</section>}
