'use client';
import {useMemo,useState} from 'react';

const AREAS=[
 {id:'in',icon:'🚚',name:'Wareneingang'},{id:'check',icon:'🔎',name:'Prüfung'},{id:'store',icon:'🏬',name:'Lager'},
 {id:'pick',icon:'🛒',name:'Kommissionierung'},{id:'pack',icon:'📦',name:'Verpackung'},{id:'out',icon:'🚛',name:'Warenausgang'}
];
const INITIAL=[
 {id:1,area:'in',kind:'damage',icon:'📦',title:'Lieferung 4711',text:'Palette sichtbar eingedrückt',due:14,correct:'check',wrong:['store'],actions:['Prüfung','Sperrlager','Einlagern']},
 {id:2,area:'in',kind:'danger',icon:'⚠️',title:'Gefahrgut-Lieferung',text:'UN 1263 · Dokumente liegen vor',due:18,correct:'check',wrong:['store'],actions:['Dokumente prüfen','Einlagern','Zurückweisen']},
 {id:3,area:'pick',kind:'express',icon:'🔴',title:'Express 381',text:'18 Positionen · Abfahrt in Kürze',due:9,correct:'pack',wrong:[],actions:['Priorisieren','Normal bearbeiten','Zurückstellen']},
 {id:4,area:'store',kind:'stock',icon:'❓',title:'A-Artikel X14',text:'Scanner: 124 · Fach: unklar',due:16,correct:'check',wrong:['pick'],actions:['Bestand prüfen','Korrigieren','Ignorieren']},
 {id:5,area:'pack',kind:'normal',icon:'📋',title:'Auftrag 377',text:'12 Positionen vollständig',due:13,correct:'out',wrong:[],actions:['Verpacken','Zurückstellen']}
];
const clamp=n=>Math.max(0,Math.min(100,n));
export default function WarehouseTycoon({onClose}){
 const [minute,setMinute]=useState(0),[jobs,setJobs]=useState(INITIAL),[selected,setSelected]=useState(null),[score,setScore]=useState(100),[quality,setQuality]=useState(100),[safety,setSafety]=useState(100),[delivered,setDelivered]=useState(0),[log,setLog]=useState([]),[done,setDone]=useState(false);
 const job=jobs.find(j=>j.id===selected);const clock=`${String(8+Math.floor(minute/60)).padStart(2,'0')}:${String(minute%60).padStart(2,'0')}`;
 const open=jobs.length;const performance=useMemo(()=>Math.round(clamp(score*.45+quality*.3+safety*.25)),[score,quality,safety]);
 function note(text,bad=false){setLog(l=>[{time:clock,text,bad},...l].slice(0,8))}
 function advance(n=2){const next=minute+n;setMinute(next);setJobs(list=>list.map(j=>({...j,due:j.due-n})));const late=jobs.filter(j=>j.due>0&&j.due-n<=0).length;if(late){setScore(s=>clamp(s-late*8));note(`${late} Vorgang${late>1?'e':''} hat die Frist überschritten.`,true)}if(next>=35)setDone(true)}
 function act(action){if(!job)return;let remove=false,bad=false,msg='';if(job.kind==='damage'){if(action==='Prüfung'){move('check');msg='Schaden dokumentiert und zur Prüfung gegeben.'}else if(action==='Sperrlager'){remove=true;msg='Beschädigte Ware sauber gesperrt.'}else{move('store');bad=true;msg='Beschädigte Ware ungeprüft eingelagert.';setQuality(q=>clamp(q-18))}}
 else if(job.kind==='danger'){if(action==='Dokumente prüfen'){move('check');msg='Gefahrgut-Unterlagen werden geprüft.'}else if(action==='Einlagern'){move('store');bad=true;msg='Gefahrgut ohne Prüfung eingelagert.';setSafety(s=>clamp(s-22))}else{remove=true;bad=true;msg='Lieferung unnötig zurückgewiesen.';setScore(s=>clamp(s-8))}}
 else if(job.kind==='express'){if(action==='Priorisieren'){move('pack');msg='Expressauftrag sofort zur Verpackung gegeben.';setScore(s=>clamp(s+3))}else if(action==='Normal bearbeiten'){move('pack');msg='Auftrag läuft normal weiter.'}else{bad=true;msg='Expressauftrag zurückgestellt.';setScore(s=>clamp(s-12))}}
 else if(job.kind==='stock'){if(action==='Bestand prüfen'){move('check');msg='Bestandsabweichung wird geprüft.'}else if(action==='Korrigieren'){bad=true;msg='Bestand ohne Prüfung korrigiert.';setQuality(q=>clamp(q-15))}else{bad=true;msg='Bestandsabweichung ignoriert.';setQuality(q=>clamp(q-10))}}
 else if(job.kind==='normal'){if(action==='Verpacken'){move('out');msg='Auftrag für den Warenausgang bereit.'}else{bad=true;msg='Fertiger Auftrag unnötig zurückgestellt.';setScore(s=>clamp(s-5))}}
 if(remove)setJobs(list=>list.filter(x=>x.id!==job.id));note(msg,bad);setSelected(null);advance(bad?4:2)}
 function move(area){setJobs(list=>list.map(x=>x.id===selected?{...x,area}:x))}
 function send(area){if(!job)return;let bad=false;if(job.area==='check'&&area==='store'){if(job.kind==='damage'){bad=false;note('Schaden erfasst, Restware freigegeben.')}else note('Prüfung abgeschlossen, Ware eingelagert.');setJobs(list=>list.filter(x=>x.id!==job.id));setQuality(q=>clamp(q+2))}
 else if(job.area==='out'&&area==='out'){setJobs(list=>list.filter(x=>x.id!==job.id));setDelivered(d=>d+1);setScore(s=>clamp(s+4));note(`${job.title} verladen und abgeschlossen.`)}
 else if(area===job.correct){move(area);note(`${job.title} → ${AREAS.find(a=>a.id===area)?.name}.`)}else{move(area);bad=true;setQuality(q=>clamp(q-7));note(`${job.title} ungünstig verschoben.`,true)}setSelected(null);advance(bad?4:2)}
 function restart(){setMinute(0);setJobs(INITIAL);setSelected(null);setScore(100);setQuality(100);setSafety(100);setDelivered(0);setLog([]);setDone(false)}
 return <section className="pressure"><header className="pressureHead"><div><span>PRAXIS-SIMULATION</span><h1>🔥 Lager unter Druck</h1><p>Keine Antwortknöpfe mit „richtig“. Entscheide selbst, was mit den Vorgängen passiert.</p></div><button onClick={onClose}>← Praxiswelt</button></header>
 <div className="pressureHud"><div><small>UHRZEIT</small><b>{clock}</b></div><div><small>OFFEN</small><b>{open}</b></div><div><small>TERMINE</small><b>{score}%</b></div><div><small>QUALITÄT</small><b>{quality}%</b></div><div><small>SICHERHEIT</small><b>{safety}%</b></div></div>
 {!done?<><div className="warehouseMap">{AREAS.map(a=><section key={a.id} className="warehouseArea"><header><span>{a.icon}</span><b>{a.name}</b><small>{jobs.filter(j=>j.area===a.id).length}</small></header><div>{jobs.filter(j=>j.area===a.id).map(j=><button key={j.id} className={`${selected===j.id?'active ':''}${j.due<=5?'urgent':''}`} onClick={()=>setSelected(j.id)}><span>{j.icon}</span><div><b>{j.title}</b><small>{j.text}</small></div><em>{j.due>0?`${j.due} min`:'ÜBERFÄLLIG'}</em></button>)}</div></section>)}</div>
 {job?<aside className="jobPanel"><div><small>AKTIVER VORGANG</small><h2>{job.icon} {job.title}</h2><p>{job.text}</p></div><div className="jobActions">{job.actions.map(a=><button key={a} onClick={()=>act(a)}>{a}</button>)}{job.area==='check'&&<button onClick={()=>send('store')}>Prüfung abschließen → Lager</button>}{job.area==='out'&&<button onClick={()=>send('out')}>Verladen & abschließen</button>}</div><div className="jobMove"><small>Vorgang verschieben</small>{AREAS.filter(a=>a.id!==job.area).map(a=><button key={a.id} onClick={()=>send(a.id)}>{a.icon} {a.name}</button>)}</div></aside>:<div className="pressureHint">👆 Wähle einen Vorgang im Lager aus. Fristen laufen mit jeder Aktion weiter.</div>}
 <div className="pressureLog"><b>Schichtprotokoll</b>{log.length?log.map((l,i)=><p key={i} className={l.bad?'bad':''}><span>{l.time}</span>{l.text}</p>):<p>Noch keine Aktionen.</p>}</div><button className="finishShift" onClick={()=>setDone(true)}>Schicht vorzeitig auswerten</button></>:<article className="pressureEnd"><span>SCHICHT BEENDET</span><h2>{performance}% Schichtleistung</h2><div><p><b>{delivered}</b><small>Aufträge abgeschlossen</small></p><p><b>{jobs.length}</b><small>Vorgänge offen</small></p><p><b>{quality}%</b><small>Qualität</small></p><p><b>{safety}%</b><small>Sicherheit</small></p></div><p>{performance>=90?'Sehr sauber. Du hast das Lager gesteuert statt nur auf Probleme zu reagieren. 🏆':performance>=70?'Solide Schicht. Im Protokoll siehst du, wo Zeit oder Qualität verloren gingen.':'Das Lager hat ordentlich zurückgeschlagen. Genau dafür ist die Simulation da. 🔥'}</p><section className="pressureLog"><b>Deine Entscheidungen</b>{log.map((l,i)=><p key={i} className={l.bad?'bad':''}><span>{l.time}</span>{l.text}</p>)}</section><button onClick={restart}>↻ Neue Chaos-Schicht</button></article>}
 </section>
}
