'use client';
import {useMemo,useState} from 'react';
const DAYS=[
 {title:'Montag · Auftragswelle',text:'Ein Neukunde schickt 35 zusätzliche Aufträge. Dein Team ist schon gut ausgelastet.',choices:[['Überstunden freigeben',-260,9,-2,8],['Priorisieren und sauber takten',-60,4,6,5],['Alles sofort durchdrücken',80,-8,-12,10]]},
 {title:'Dienstag · Engpass im Wareneingang',text:'Zwei LKW stehen gleichzeitig am Tor. Ein dritter ist angekündigt.',choices:[['Aushilfe für den Tag buchen',-220,8,2,7],['Zeitfenster neu koordinieren',-40,2,7,3],['Fahrer warten lassen',0,-7,-8,-6]]},
 {title:'Mittwoch · Stapler macht Geräusche',text:'Der meistgenutzte Stapler klingt nicht gesund. Heute stehen viele Bewegungen an.',choices:[['Wartung sofort beauftragen',-380,5,8,-4],['Reservegerät mieten',-240,6,5,2],['Weiterfahren bis er ausfällt',0,-10,-15,8]]},
 {title:'Donnerstag · Schnelldreher',text:'Artikel X-14 verursacht lange Laufwege und wird ständig kommissioniert.',choices:[['Lagerplatz dauerhaft optimieren',-180,3,8,8],['Nur heutige Ware vorziehen',-40,1,2,5],['Nichts ändern',0,-2,-5,-5]]},
 {title:'Freitag · Reklamation',text:'Ein wichtiger Kunde meldet drei beschädigte Sendungen aus dieser Woche.',choices:[['Ursache analysieren und Verpackung anpassen',-210,5,12,-2],['Gutschrift senden, Prozess unverändert lassen',-150,1,-4,2],['Reklamation zurückweisen',0,-12,-12,0]]},
 {title:'Samstag · Investition',text:'Du hast ein Angebot für neue Scanner. Sie würden Buchungsfehler reduzieren.',choices:[['Scanner anschaffen',-650,3,12,7],['Pilot mit zwei Geräten starten',-280,2,7,4],['Investition verschieben',0,0,-2,0]]},
];
const clamp=n=>Math.max(0,Math.min(100,n));
export default function WarehouseTycoon({onClose}){const [day,setDay]=useState(0),[money,setMoney]=useState(4200),[team,setTeam]=useState(68),[quality,setQuality]=useState(70),[flow,setFlow]=useState(62),[history,setHistory]=useState([]),[done,setDone]=useState(false);const event=DAYS[day];const company=useMemo(()=>Math.round((team+quality+flow)/3),[team,quality,flow]);function choose(c){setMoney(x=>x+c[1]);setTeam(x=>clamp(x+c[2]));setQuality(x=>clamp(x+c[3]));setFlow(x=>clamp(x+c[4]));setHistory(h=>[...h,{day:event.title,choice:c[0],cash:c[1]}]);if(day===DAYS.length-1)setDone(true);else setDay(d=>d+1)}function restart(){setDay(0);setMoney(4200);setTeam(68);setQuality(70);setFlow(62);setHistory([]);setDone(false)}return <section className="tycoon"><header className="tycoonHead"><div><span>MANAGEMENT-SIMULATION</span><h1>🏢 Lagerleiter</h1><p>Eine Woche. Ein Lager. Deine Entscheidungen wirken weiter.</p></div><button onClick={onClose}>← Aktivitäten</button></header><div className="tycoonStats"><div><small>KASSE</small><strong>{money.toLocaleString('de-DE')} €</strong></div><div><small>TEAM</small><strong>{team}%</strong></div><div><small>QUALITÄT</small><strong>{quality}%</strong></div><div><small>PROZESS</small><strong>{flow}%</strong></div></div>{!done?<><div className="tycoonPlant"><div className="tycoonBuilding"><span>LOGISTIKZENTRUM</span><div>▦ ▦ ▦</div><b>🚚</b><i>📦</i></div><div className="tycoonPulse"><small>BETRIEBSSTATUS</small><strong>{company>=80?'Läuft rund 🟢':company>=60?'Unter Kontrolle 🟡':'Kritisch 🔴'}</strong><div><span style={{width:`${company}%`}}/></div></div></div><article className="tycoonEvent"><span>TAG {day+1} / {DAYS.length}</span><h2>{event.title}</h2><p>{event.text}</p><div>{event.choices.map((c,i)=><button key={i} onClick={()=>choose(c)}><b>{c[0]}</b><small>{c[1]===0?'Keine direkten Kosten':`${c[1].toLocaleString('de-DE')} €`}</small></button>)}</div></article></>:<article className="tycoonEnd"><span>WOCHENBERICHT</span><h2>{company}% Unternehmensleistung</h2><p>{company>=82&&money>1500?'Stark geführt. Qualität, Mannschaft und Durchsatz sind gleichzeitig stabil. 🏆':company>=65?'Der Betrieb steht, aber einige Entscheidungen haben Spuren hinterlassen.':'Das Lager läuft im roten Bereich. Hier braucht es eine neue Strategie. 🚨'}</p><div className="tycoonReport"><div><small>Endbestand Kasse</small><b>{money.toLocaleString('de-DE')} €</b></div><div><small>Entscheidungen</small><b>{history.length}</b></div></div><div className="tycoonHistory">{history.map((h,i)=><div key={i}><span>{i+1}</span><p><b>{h.day}</b><small>{h.choice}</small></p><strong>{h.cash===0?'±0 €':`${h.cash>0?'+':''}${h.cash} €`}</strong></div>)}</div><button className="tycoonAgain" onClick={restart}>↻ Neue Woche</button></article>}</section>}
