import { v04Questions } from '../app/questions-v04.js';
import { v05Questions } from '../app/questions-v05.js';
import { v06Questions } from '../app/questions-v06.js';
import { v07Questions } from '../app/questions-v07.js';
import { wisoQuestions } from '../app/questions-wiso-v110.js';
import { createCalculationQuestions } from '../app/data.js';
import { qualityCheckedQuestions } from '../app/question-quality-filter.js';
import { finalAuditQuestions } from '../app/question-audit.js';
export const raw = [...v04Questions,...v05Questions,...v06Questions,...v07Questions,...createCalculationQuestions(20260915),...wisoQuestions];
export const active = finalAuditQuestions(qualityCheckedQuestions(raw));
